### ISSUE TITLE
Have no-collisions apply to Citizens player-based NPCs

### ISSUE THREAD

**Issue by Formula350** [kernitus/BukkitOldCombatMechanics#134]
As per gvlfm78's request, I'm opening a few Issues regarding questions which may or may not be bug related....

OCM v1.6.2 build 60 (tried build 8, v1.6.1, v1.4.2, v,1.1.2)
Spigot 1.11.2 as far as I know (git-Spigot-3fb9445-6e3cec8)
Citizens 2.0.22 Build #1491

Partially references #114 which asks to prevent **all** Collisions. However, are Citizens NPCs, which are Player-based, supposed to be colliding even when the current OCM Collisions option is set to disable collisions?
 As far as the Citizens NPCs go, you can walk through them *only as long as you commit to moving!* If you stop while part way through, then the collision kicks in and moves one of you.

This only occurs on Citizen NPCs. Every other animal or mob, you collide with and the physics moves one of you. With real-players, you just pass right through them as you did in 1.8. As such, it almost feels like OCM considers the Citizens entity to be BOTH a Player and a Non-Player, hence why it allows you to pass-through up until the moment you stop moving.

**Comment by Rayzr522** [comment]
Citizens is some seriously sucky stuff. Here is what is happening (99% sure): Citizens is spawning fake players, which are not being placed in the `ocmInternal` team. So, @gvlfm78, you need to find a way to place all Citizens NPC fake players into the team. If you can’t get that to work, then I think you’re pretty much screwed. Disabling player collisions via a scoreboard team only works if it’s applied to both players in a collision.

**Comment by gvlfm78** [comment]
A few versions ago I changed the way the no-collisions module works. I removed the `ocmInternal` team-based system and switched to sending a packet to the player as soon as they login that the team they're in has the no-collisions flag activated. I cannot remember the exact way in which it works right now but it may be possible to send these packets to other entities too, but the effects of that are unpredictable, as is using reflection with the internal Minecraft API.

**Comment by Formula350** [comment]
lol To be fair, from my understanding at least, Bukkit and Plugins, on the whole, are "hacky" in how they manipulate MC to do all the wonderful things you Devs have allowed us to do with our servers. :) Alas, yea, no doubt that there are varying degrees of it, minimal to rather extreme cases... heh

Would it be possible to provide additional/better support for this if the server is using ProtocolLib? Not to say that it'd be required in any way, completely optional of course, but it seems like with so many plugins that do utilize it that it means plenty of servers have it loaded anyways. Could even be a config option, either per-category such as `ProtocolLibCollisions: <enable|disable>`, or a global switch like `ProtocolLibSupport: <enable|disable>`.

**Comment by gvlfm78** [comment]
IIRC all ProtocolLib does is provide an interface between the internal Minecraft Net server code and other plugins. This has the advantage that plugins can use the internal methods without needing to update every new Bukkit update or use reflection to access these methods without having to update. But OCM already uses reflection...

**Comment by kernitus** [comment]
This does not affect combat so I don't believe is a large enough issue to warrant messing around with packets and Citizens.
