### ISSUE TITLE
Weapon click spam

### ISSUE THREAD

**Issue by NelsonHD** [kernitus/BukkitOldCombatMechanics#148]
Version of Bukkit/Spigot : git-Spigot-7754231-a3b3a42 (MC: 1.12.2)
Version of OCM plugin : 1.6.2
Config : https://pastebin.com/UpyXYbmN
Error log : NULL
-----------------
If player use the gun which make by CrackShot, use the gun and sword to attack mobs, the cooldown wont work in that 1~2 sec. 100~150 damage / 1s

**Comment by gvlfm78** [comment]
__What__ happens when you use __what__ weapon?

**Comment by NelsonHD** [comment]
normal diamond sword with mouse clicker

**Comment by gvlfm78** [comment]
Is this the case even with a normal weapon?

**Comment by NelsonHD** [comment]
Ys
And here is the video about diamond sword with damage 80
https://drive.google.com/file/d/1_f_VfNSiZe9k1JquOLA3MZe4LwT6qOAw/view
