### ISSUE TITLE
Custom EnderPearl cooldown

### ISSUE THREAD

**Issue by Ahstval** [kernitus/BukkitOldCombatMechanics#169]
How about adding cooldowns that apply to enderpearl/enchanted golden apple usage ? with customizable cooldowns and messages ? I think that would be dope especially knowing that as soon as I activate the "old golden apple" option, any cooldown plugin I use doesn't work.. well it kinda does as it shows the messages but the apple is actually eaten and the effects reset; but as soon as I deactivate it, everything is normal and the cooldowns work.. So adding an option in within this plugin would be dope !

**Comment by gvlfm78** [comment]
So you wish to allow the customisation of cooldown for gapples and enderpearls?

**Comment by Ahstval** [comment]
Yeah exactly if possible ! That would be dope <3

**Comment by gvlfm78** [comment]
Moved gapple cooldown to #122
