### ISSUE TITLE
Enable or disable plugin function for different clients version

### ISSUE THREAD

**Issue by imfrea** [kernitus/BukkitOldCombatMechanics#222]
## Info

- Server version: 1.12.2
- OldCombatMechanics version: 1.6.6
- Server log file: 
- OldCombatMechanics config file: 

## Problem Description
Some servers have multiple version support , if OldCombatMechanics can Hook into ProtocolSupport/Viaversion to check players's clients version , and disable OldCombatMechanics for 1.9 and newer clients , just enable OldCombatMechanics for 1.8.9 and Legacy clients .
If this can be achieved , the plugin will more perfect !
>

**Comment by elstur** [comment]
This sounds like you're asking for OldCombatMechanics to make 1.8.9 clients use 1.9+ mechanics, which is the opposite of what the plugin does. The plugin changes the server side mechanics for 1.9+ to make it like 1.8.

**Comment by Rayzr522** [comment]
OldCombatMechanics only functions for 1.9 and newer clients because older versions already have the old mechanics. As @elstur said, are you trying to get 1.9+ combat for 1.8 and older clients?

**Comment by LoveFrea** [comment]
I didn't mean that. 
I mean , 1.9-latest clients use 1.9+ combat (disabled plugin function for these players), 1.8.9-legacy clients use old combat .

**Comment by VaiTon** [comment]
So it would mean that some 1.8-combat players could fight with some 1.9-combat players. Same problem as [here](https://github.com/gvlfm78/BukkitOldCombatMechanics/issues/179#issuecomment-443530585).

**Comment by kernitus** [comment]
Merging into #179
