### ISSUE TITLE
Golden Apples blocking Advancements

### ISSUE THREAD

**Issue by northerncarrots** [kernitus/BukkitOldCombatMechanics#317]
## Info

- Server version: 1.13.2
- OldCombatMechanics version: 
- Server log file: (No logs)
- OldCombatMechanics config file: https://pastebin.com/raw/FV20YcnA

## Problem Description
> Eating old golden apples prevent players from adding one golden apple eaten to their statistics, preventing progression on the "A Balanced Diet" advancement.

Changing `old-golden-apples enabled` from **true** to **false** fixes the problem.

**Comment by gvlfm78** [comment]
This is because the eating event is cancelled so custom effects can be applied. I guess a possible solution is to forcibly award the advancement whenever a golden apple is eaten.  
A better solution would be to tell the server that the player ate an apple, which I am not sure on how to do.

**Comment by gvlfm78** [comment]
@northerncarrots This should now be fixed in [test build 64](https://ci.rayzr.dev/job/OldCombatMechanics/64/). Please test it out, I made it so both player statistics and advancement progress are incremented by the plugin after the event is cancelled.

**Comment by northerncarrots** [comment]
Extremely sorry for the late answer.
It seems to be working now. Thank you.

There is one more issue (although it does not pose a big problem). Consuming a golden apple in creative mode will still decrease the item count by one.
Vanilla behavior will keep the item count the same when consuming a golden apple.
