### ISSUE TITLE
Eggs and snowballs knockback not always working

### ISSUE THREAD

**Issue by AlxC01** [kernitus/BukkitOldCombatMechanics#327]
## Info

- Server version: Paper-1606 (MC: 1.12.2)
- OldCombatMechanics version: version: 1.7.4-BETA
- Server log file: https://pastebin.com/cbsnzSqp
- OldCombatMechanics config file: https://pastebin.com/9nHhTevH

## Problem Description
> Hello!

I have errors with the knockback, I have talked with the guys of the via version and they tell me that you could solve these problems again. I am using ViaBackwards, Via Rewind and ViaVersion in the latest version. Could you give me a hand? Sometimes they work and sometimes they don't work.

Thank you very much for reading me!

**Comment by gvlfm78** [comment]
1. What is the exact behaviour you want, and what is instead happening?
2. Why do you say ViaBackwards, Via Rewind and ViaVersion are partly responsible?

**Comment by AlxC01** [comment]
Hello!

In the beginning, if you shoot someone with a snowball or with an egg, you should first push him, in this case, you will shoot someone with an egg / snowball and sometimes it works and it is often like It has a protective layer and does NOT touch. At first, it should act like a normal egg / level ball. Don't you think

**Comment by AlxC01** [comment]
If you want to check it, I recommend that you play a few games on my server, mc.minebox.es> SkyWars. You can see how sometimes it works well and sometimes not. Thank you

**Comment by gvlfm78** [comment]
I did not understand. What would you _like_ the behaviour to be?
