### ISSUE TITLE
Gapple Cooldown issue

### ISSUE THREAD

**Issue by OpvpYT** [kernitus/BukkitOldCombatMechanics#341]
OldCombatMechanics break the cancel event of all GoldenApple cooldowns plugins.
Only when old-gapple is enabled in config, there is no way to use a plugin to cancel the eat event.

This bug is on the latest version of OCM and I tested it on paper 1.11.2 and 1.12.2.

- Server version: 1.12.2
- OldCombatMechanics version: 1.7.4
- OldCombatMechanics config file: https://pastebin.com/qQbHLSRv

## Problem Description
> 
OldCombatMechanics break the cancel event of all GoldenApple cooldowns plugins.
Only when old-gapple is enabled in config, there is no way to use a plugin to cancel the eat event.

This bug is on the latest version of OCM and I tested it on paper 1.11.2 and 1.12.2.

**Comment by I-Al-Istannen** [comment]
OCM should probably either listen on HIGH/HIGHEST and *respect the cancel status of the event* or do not modify the consume event at all (listen on monitor) and just overwrite the effects a tick later. The first solution is probably nicer, the second is tad more compatible. Though a cooldown plugin really ought to listen on a low priority so I'd expect the first change (just an `isCancelled` check) to be enough.

**Comment by gvlfm78** [comment]
@I-Al-Istannen OCM already listens on HIGH, I'll just add a check to not do anything if the event is already cancelled.

**Comment by gvlfm78** [comment]
@OpvpYT Please try if [test build 63](https://ci.rayzr.dev/job/OldCombatMechanics/63/) fixes the issue, I have set OCM to ignore the event if it has already been cancelled.

**Comment by lucas2107** [comment]
I tried with my own plugin, still not working.

**Comment by lucas2107** [comment]
It seems not working for me...

Tried using Highest priority and cancel it, nothing to do :/

**Comment by kernitus** [comment]
@lucas2107 if you're making a cooldown plugin, it should probably be on low priority. Highest would mean it runs after OCM has already done its thing on high.

**Comment by lucas2107** [comment]
My bad. I will try it...

**Comment by lucas2107** [comment]
Still having the same problem in LOW priority.

**Comment by kernitus** [comment]
@lucas2107 are you cancelling the event, or modifying it?

**Comment by lucas2107** [comment]
cancelling

**Comment by kernitus** [comment]
From commit c9a1344 OCM allows customising the gapple cooldown. If this is still a problem then please open an issue as an incompatibility with a specific plugin.
