### ISSUE TITLE
Shields not working

### ISSUE THREAD

**Issue by YazTDB** [kernitus/BukkitOldCombatMechanics#342]
Lately I got this plugin on my server, it all worked fine. One of my friends told me there was  an issue with shields (I edited the config file to allow shields and the off-hand to be used as well as disabling the right click to block with 'sword'). My friend told me that the shields didn't work for her. It was odd since me and another friend never had an issue. But 2 other people were having the same issue. I don't know if it's an issue with the client or the server, but it's been happening ever since we got this plugin.

**Comment by gvlfm78** [comment]
Well you haven't actually explained what the issue is, "shield not working" is equivalent to going to the doctor and saying "I'm sick, please give me some medicine".
What exactly happens that shouldn't, how and when?

**Comment by YazTDB** [comment]
The shields act as if they're not there. Say if there is a skeleton shooting, the arrow will just hit the player instead of being deflected. This happens with only a few players and I cannot figure out why. I'm very new to plugins. If I've not explained it clearly enough again, please tell me. I'm sorry I didn't explain fully the first time

**Comment by kernitus** [comment]
Ok @YazTDB can I know what version of the plugin and of Bukkit/Spigot/Paper you're using?

**Comment by YazTDB** [comment]
Spigot 1.14, but after jigging with some settings the issue seems to have resolved and the shields are now working. Sorry for the trouble!
