### ISSUE TITLE
Shields are not working with armor

### ISSUE THREAD

**Issue by uruhara** [kernitus/BukkitOldCombatMechanics#346]
- Server version: git-Spigot-065a373-9aa7430 (MC: 1.14.4)
- OldCombatMechanics version: 1.7.5BETA (tested even on 1.7.4)
- Server log file: I think thats not important since there is no error here, and was tested without any plugins.
- OldCombatMechanics config file:  
- tested on: 
  - Default  cfg
  - Default with generalDamageReduction: 1 and projectileDamageReduction 1

## Problem Description
> Well, everything works as it should without armor. The problem begins when I put armor on. 
I have tested the damages with MythicMobs plugin since I couldnt turn off the plugins atm.

Explosion damage: I have set creeper damage on 100 => even when you equip full diamond you die instantly.
Without armor and with shield: dmg was like 3-8 hp
Without armor and without shield: Instant death
With armor and without shield: Instant death
With armor and with shield: No damage, only shield and armor are taking damage.
BAD

Now for the projectiles. I have used regular skeleton with a power IV bow
Without armor and with shield: 4 hp
without armor and without shield: 4 hp
with armor and without shield: 1 hp
with armor and with shield: 1 hp
That is OK!

Now for the melee damage: Zombie with iron sword sharpness III
Without armor and with shield: 5 hp
Without armor and without shield: 10 hp
With armor and Without shield: 2 hp
With armor and With shield: No damage, only shield and armor are taking damage
And this is BAD again?

If i turn off all the plugins, the damage is different in numbers but the result is same...
I think I am not messing up anything and hope that we will solve the problem! Thank you!

**Comment by kernitus** [comment]
You should be testing this with `debug: enabled` in the config.yml, so we can see the actual damage values the plugin applies.
