### ISSUE TITLE
 PvP is not changed when changing maps

### ISSUE THREAD

**Issue by TooruTNT** [kernitus/BukkitOldCombatMechanics#348]
## Info

- Server version: 
- OldCombatMechanics version: 
- Server log file: 
- OldCombatMechanics config file: 

## Problem Description
> The plugin is fine, but my problem is that when switching to a pvp map with 1.14 (coldown), it is maintained with 1.8 pvp. I currently use a plugin called PerWorldPlugins, because in the config of the plugin, although I put the disable-coldown for some maps, it does not work and puts it in pvp of 1.8 for the entire server. The problem I have right now is that being in a world without coldown and going to a world that does have a coldown ... the pvp is maintained with 1.8, and to return to normal (pvp 1.14), it is necessary to disconnect to be pvp 1.14 again in the worlds, whether survival, skyblock, etc.

Atte: TooruTNT

**Comment by kernitus** [comment]
You should be using OCM's `worlds:` list in the `config.yml` to specify what worlds you want the plugin to run in.

**Comment by TooruTNT** [comment]
That's what I did, but it still doesn't work for me. That's why I turned to the PWP plugin and that's when it just worked for me, but with the detail I wrote before. That the pvp remains at 1.8 despite the fact that you change the world to one with cooldown. The version I use on my server is 1.14.3

**Comment by kernitus** [comment]
PWP might be interfering, you should be using the `worlds:` list.

What does your `worlds:` list currently contain?
