### ISSUE TITLE
Bedwarsrel issue

### ISSUE THREAD

**Issue by laughskate** [kernitus/BukkitOldCombatMechanics#352]
## Info

- Server version: 
- OldCombatMechanics version: 
- Server log file: 
- OldCombatMechanics config file: 

## Problem Description
>  Basically I use a plugin called bedwarsrel and whenever the game ends I fall through the void in spectator mode. When i uninstalled this plugin the issue was fixed. I really like this plugin and I hope you can fix this asap.

**Comment by Rayzr522** [comment]
Sorry to hear you are having these issues! Could you please confirm your Minecraft server version and your OldCombatMechanics version? You can check them via `/version` and `/version OldCombatMechanics` respectively.
