### ISSUE TITLE
Haste/Mining fatigue should be togglable for attackSpeed

### ISSUE THREAD

**Issue by FnarGod** [kernitus/BukkitOldCombatMechanics#354]
## Info

- Server version: 1.13.2
- OldCombatMechanics version: latest
- Server log file: 
- OldCombatMechanics config file: 

## Problem Description
> In the plugin, you have disabled mining fatigue and haste from affecting the attack speed which is good. But you have made so many things togglable within the config. I need that to be changeable to true so I can still have haste or mining fatigue affect the attackspeed for a player. Right now (In classic 1.8 fashion) it doesn't affect attackspeed at all but I would really like a way to disable that specific thing so it DOES affect attack speed. All the other potion effects are togglable please help me with this.

**Comment by kernitus** [comment]
Have you changed anything in the config that would affect this?

**Comment by kernitus** [comment]
I just tested this. Haste _does_ affect the attack speed, as it should in 1.9+.
