### ISSUE TITLE
Errors in console

### ISSUE THREAD

**Issue by Devillion** [kernitus/BukkitOldCombatMechanics#356]
## Information

* Server Version:  1.13.2

* OldCombatMechanics version: 1.7.4

* Server Log File: https://pastebin.com/gWS3T8bD

* OldCombatMechanics config file: https://pastebin.com/P4M6KFkG

## Problem Description

I don't really know what the bug is, it just happens while playing.

 
### To Reproduce
1. I'm not really sure how it's happening or what makes it happen.

**Comment by kernitus** [comment]
Why did you write down you're using OldCombatMechanics version 1.7.4 when the error log clearly shows it's from version 1.6.6?
