### ISSUE TITLE
Question about config settings

### ISSUE THREAD

**Issue by zeronerve** [kernitus/BukkitOldCombatMechanics#357]
In the setting below, if "enabled" is set to "false", will the the attack cooldown will still be active/enabled,? I know this is basic stuff, but I'm making changes to these settings and using /ocm reload, but I'm not seeing the difference. Just wondering if you could clarify how this is supposed to work since we are "enabling" a "disable".

disable-attack-cooldown:
  enabled: false
  worlds: []
  generic-attack-speed: 4

More specifically, what settings do you recommend here to achieve the closest mechanics to 1.8.9 pvp?

**Comment by zeronerve** [comment]
After looking at your module, class I understand the settings, but I'm having trouble seeing the changes take affect. Does a /ocm reload apply changes immediately for a 1.14.4 server build?

**Comment by kernitus** [comment]
Yes, it does.

**Comment by zeronerve** [comment]
what settings do you recommend here to achieve the closest mechanics to 1.8.9 pvp?

**Comment by Rayzr522** [comment]
The default settings should be the closest to 1.8.9 PVP. However, for a full 1.8.9 experience, you may wish to also enable `disable-player-collisions`, `no-lapis-enchantments`, and `disable-elytra`. (you can also turn on `disable-bow-boost` and `chorus-fruit.prevent-eating`, but these have very little impact on the game)
