### ISSUE TITLE
Passive Regeneration is off when the plugin is active.

### ISSUE THREAD

**Issue by ItzVinex** [kernitus/BukkitOldCombatMechanics#358]
Passive Regeneration is off when the plugin is active. I have removed the plugin and I can regenerate again. 1.14.4 with ViaVersion. No errors in the console.

**Comment by kernitus** [comment]
What do you mean by 'off'? There's an old-regen module you might want to change the settings of

**Comment by ItzVinex** [comment]
Literally, with the old regen turned off you regenerate health, with it toggled one you simply do not.

**Comment by ItzVinex** [comment]
on*

**Comment by kernitus** [comment]
You do not regenerate health at all, under any circumstances?

Can you please turn on debug mode in the config, and check the debug messages with the regen module enabled, right after you get damaged?
