### ISSUE TITLE
No damage with egg, snowball projectiles under Absorption effect

### ISSUE THREAD

**Issue by telfrancesco** [kernitus/BukkitOldCombatMechanics#361]
* Server Version: 
[19:13:27] [Client thread/INFO]: [CHAT] This server is running Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[19:13:27] [Client thread/INFO]: [CHAT] Previous version: git-Paper-1618 (MC: 1.12.2)

* OldCombatMechanics version: 
1.7.4

* OldCombatMechanics config file: 
https://pastebin.com/iWbT8Q4A
## Problem Description
When a player have Absorption effect, it dosen't take knockback, or "damage" it only with projectile as: egg, snowball, energy. P.s Help me i have a faction server with (paperspigot 1.12.2 for optimization) and i need snowball, egg, ecc ecc.

https://youtu.be/0R8-t64ygzw

**Comment by barpec12** [comment]
This happens only when player has over than 20 hp, on 20hp with absorbtion effect everything works

**Comment by barpec12** [comment]
When changing snowball damage to 4.1 knockback works. When player has over 20 hp and the damage is set to 2 for example, he only reveives damage, without knockback.

**Comment by barpec12** [comment]
It works the same way with https://github.com/klokailo/ProjectileKnockback, maybe bukkit does something different when player has over 20hp and receives damage.

**Comment by kernitus** [comment]
Fixed with 10a790a
