### ISSUE TITLE
Change Trident Damage

### ISSUE THREAD

**Issue by Rabidhuman** [kernitus/BukkitOldCombatMechanics#362]
Please let us change these damages for these weapons. It is pretty OP to use them.
It takes about 8 diamond sword hits on my server to get a mob, but only 2 trident hits.

Thanks for your time!

**Comment by Rabidhuman** [comment]
Bump

**Comment by Rabidhuman** [comment]
Hi! Wondering if this plugin is discontinued for updates.

**Comment by kernitus** [comment]
> Hi! Wondering if this plugin is discontinued for updates.

Absolutely not! We are just extremely busy at the moment.  
Can I have a few more details about what exact feature you're looking for? You mention both trident and bows in the title, but mainly focus on the trident.  
I am going to change this report to be only about tridents for ease of implementation. You can open a new one about bows if you like.

**Comment by kernitus** [comment]
This can also be considered feature creep - if anything we should have a module to block the usage of certain weapons if they did not exist in 1.8.
