### ISSUE TITLE
Configurable Enchantment Damage

### ISSUE THREAD

**Issue by Rabidhuman** [kernitus/BukkitOldCombatMechanics#364]
Please let us nerf enchantments alongside weapons. Often swords are outputting too much dmg.

## Problem
A 2 dmg set diamond sword suddenly does a lot more than i want it to

## Proposed solution
 Let us change the ratio

**Comment by kernitus** [comment]
This would be feature creep, I do not think enchantments changed drastically from 1.9 onwards.
