### ISSUE TITLE
MythicMobs

### ISSUE THREAD

**Issue by tanderman** [kernitus/BukkitOldCombatMechanics#368]
Ho un problema con mythicmobs relativo a questo plugin, se io ho instato questo plugin sul mio server le skill dei miei mob fatte con mythicmobs si buggano, e ogni volta che ne fanno una gli si rigenera tutta la vita,anche se la skill dovrebbe fare una cosa del tutto diversa.Ho provato a togliere il plugine e le skill hanno ripreso a funzionare correttamente.Sistemate il problema per favore

**Comment by Rayzr522** [comment]
Please submit your issue reports in English if possible, I tried using Google Translate on your comment but it didn't seem to work on a lot of words.
