### ISSUE TITLE
Particle effect is not removed

### ISSUE THREAD

**Issue by Lunatik934** [kernitus/BukkitOldCombatMechanics#370]
## Information

* Server Version: 1.12.2

* OldCombatMechanics version: 1.7.5BETA

* Server Log File: nothing

* OldCombatMechanics config file: 

disable-sword-sweep:
  enabled: true
  worlds: []

## Problem Description

Particle effect is not removed when I set true in disable-sword-sweep, heart particles spawn..
 
### To Reproduce
1. hit monster with sword

**Comment by kernitus** [comment]
Well... It works fine here, any more details you could give us?
