### ISSUE TITLE
Disable Barrels

### ISSUE THREAD

**Issue by N0tMyFaultOG** [kernitus/BukkitOldCombatMechanics#372]
## Problem
You can luckily disable any item behavior unless barrels.

## Proposed solution
Having a config option to disable barrel interaction.

**Comment by kernitus** [comment]
You mean when you right click? Can't you just add that in the `interactive` list?

**Comment by N0tMyFaultOG** [comment]
> You mean when you right click? Can't you just add that in the `interactive` list?

I added it but I can still interact with them.

**Comment by kernitus** [comment]
Barrel has been added to interactive list with c6d0b67
