### ISSUE TITLE
Spam clicking doesn't seem to do as much damage

### ISSUE THREAD

**Issue by MilkLegend** [kernitus/BukkitOldCombatMechanics#373]
Is there a way to disable 1.12.2 damage? (When you spam click, you will deal less damage then clicking 3 CPS) and change it back to 1.8.9 damage?

**Comment by kernitus** [comment]
Sorry but I don't actually understand the question here, what do you mean by 1.12 damage vs 1.8 damage? The plugin already changes the damage to the 1.8 equivalent.

**Comment by MilkLegend** [comment]
Hmm, I've been 1v1ing with a friend, he doesn't spam click but I do, I only really do 5 hearts, when I don't spam click, I kill him.

**Comment by Rayzr522** [comment]
That's not a very scientific test -- the only real way to test this is two hits in quick succession vs two hits slowly (making sure that neither are crit hits or anything else is different). 

If that reveals that there is still genuinely a difference then that means something is either wrong with your OCM config or OCM isn't loading. A complete logfile would be greatly beneficial.

**Comment by kernitus** [comment]
This may be somewhat related to the damage immunity, as outlined in #381.
