### ISSUE TITLE
shield-damage-reduction giving extra or no damage

### ISSUE THREAD

**Issue by northerncarrots** [kernitus/BukkitOldCombatMechanics#378]
## Information

* Server Version: 1.15.2

* OldCombatMechanics version: v1.7.5BETA

* Server Log File: Unable to retrieve at this time

* OldCombatMechanics config file: https://pastebin.com/raw/P102xQEc

## Problem Description

**IF old-armour-strength is enabled:**
Equipping armor up to 12 (6 armor bars) would completely null all damage and allow any player equipping any tool/weapon to combo a player infinitely into the air (as if they did not have any invincibility frames from being attacked)

**IF old-armour-strength is disabled:**
Players take extra damage when shielding.
A player wearing full diamond armor will receive 1 (0.5 armor bar) of damage when being punched with a fist.

The **shield-damage-reduction** module is broken in general as of this version.
Changing the values barely changes anything while old-armour-strength is enabled.
Changing the values does not change anything while old-armour-strength is disabled.

 
### To Reproduce
1. Enable or disable *old-armour-strength*
2. Enable *shield-damage-reduction*
3. Attack players with their shield up

### Expected Behaviour
Damage gets reduced based on the value given

### Actual Behaviour

Either no damage (old-armour-strength enabled) is given and players get no invincibility frames from being attacked
OR
extra damage (old-armour-strength disabled) is given
Value does not affect damage given at all/most of the time

**Comment by kernitus** [comment]
Can you please enable `debug` mode in the config and provide some logs for these situations?

**Comment by northerncarrots** [comment]
[**old-armour-strength** enabled
**shield-damage-reduction** enabled](https://pastebin.com/raw/MekCBNwT)

**old-armour-strength** **_disabled_**
**shield-damage-reduction** enabled
[**fists**](https://i.imgur.com/mVhhQbE.png)
(8-8.5/10.0 hearts left on 5 hits)
[**Diamond Sword**](https://i.imgur.com/Jqncj7n.png)
(died after 5 hits)
(Logs would not appear in console, only in game chat)

[**shield-damage-reduction disabled
old-armour-strength enabled**](https://pastebin.com/raw/fBgGQn1X)

I am mainly looking for this issue to be fixed with
**shield-damage-reduction** _enabled_
and
**old-armour-strength** _enabled_
as it resembles old combat mechanics more. 

Having shield-damage-reduction enabled just makes you take no damage and gives no invincibility frames (which allows you be combo'd into the air indefinitely by someone with a high click rate).

Having old-armour-strength disabled does not show debug messages in the console.

The damage values are very strange. You take more damage by a fist when shielding but less when hit by a sword.

**Comment by kernitus** [comment]
Cannot reproduce. Maybe enough changed in-between versions that this does not apply anymore.
