### ISSUE TITLE
Hit registration

### ISSUE THREAD

**Issue by blakep-dev** [kernitus/BukkitOldCombatMechanics#379]
## Information

* Server Version: Paper 1.15.2

* OldCombatMechanics version: 1.7.4

* Server Log File: No errors

* OldCombatMechanics config file: https://pastebin.com/RdXVwMUK

### To Reproduce
1. Get in combat
2. Start to attack
3. Be attention to when you can actually hit

### Expected Behaviour
It's expected that every hit registers. The TPS is at 20.0

### Actual Behaviour

Instead, there are times where people cant attack eachother for a few seconds

![image](https://user-images.githubusercontent.com/53025771/80531433-a1a87f80-8968-11ea-8a66-af90097802e1.png)

**Comment by SladeHazard** [comment]
Try without oldcombatmechanics and see if works fine!

**Comment by Ruymanphone** [comment]
I have the same problem but I think it is the combat log because I had no problems with the old combat mechanics before installing it, so I don't know

**Comment by Ruymanphone** [comment]
I mean an issue where the players seem immortal

**Comment by kernitus** [comment]
You must try without OCM, then with OCM but without other combat plugins, as often there can be conflicts between such plugins and it's not really either plugin's fault.

**Comment by kernitus** [comment]
Also, please make sure it's not just the 1.8 damage immunity, as in issue #381.
