### ISSUE TITLE
Damage immunity not working possibly because of OldCombatMechanics

### ISSUE THREAD

**Issue by lenis0012** [kernitus/BukkitOldCombatMechanics#381]
## Information

* Server Version: 1.13.2

* OldCombatMechanics version: #2

* Server Log File: https://pastebin.com/DZ0J6Jn2
this is during the relevant time of the incident

* OldCombatMechanics config file: https://pastebin.com/

## Problem Description

Players are able to git a double hit in < 0.5 seconds
see https://gyazo.com/7b387a2799e66d315c6f38134c2c0947

 
### To Reproduce
1. try hitting a player with very high cps. This player says he can click up to 20x per second, but typically around 14.

### Expected Behaviour
At least 0.5 sec between hits because of damage immunity

### Actual Behaviour

it seems damage immunity does not always work. this player was able to get 2 hits almost instantly

plugins: ProtocolSupport, ViaVersion, AAC, AACAdditionPro, ConditionalCommands, AACPlus, ProtocolLib

**Comment by kernitus** [comment]
I'm not sure what you mean here - players _can't_ get a high hits per second and they should, or the other way around?

**Comment by lenis0012** [comment]
@kernitus 1.8 does not have cooldown, that is how it is supposed to be.
Instead, there is damage immunity.

Players should NOT be able to be hit more than once per 0.5 seconds.
It appears they can sometimes, which is wrong.

**Comment by lenis0012** [comment]
fights are lasting super short sometimes because fast players get 2 hits in at once.

**Comment by kernitus** [comment]
I don't believe that's how damage immunity works, the [Minecraft Wiki for 1.8](https://minecraft.gamepedia.com/index.php?title=Damage&oldid=950696#Damage_immunity) says that if the damage dealt is higher than the previous damage then it is still applied. The [newer wiki](https://minecraft.gamepedia.com/index.php?title=Damage#Immunity) says the damage difference is applied.

**Comment by lenis0012** [comment]
@kernitus It appears you are correct, I don't know why I didn't check the wiki for 1.8, I just assumed damage immunity had not changed.

Thank you very much for determining the cause, and I sincerely apologize for opening a false report.

I suppose i'll have to keep looking why some of our players are reporting PVP is feeling shorter than on other 1.8 servers. Maybe they're just imagining things.
