### ISSUE TITLE
Players become invisible when doing sword-blocking

### ISSUE THREAD

**Issue by EdgarGDE** [kernitus/BukkitOldCombatMechanics#382]
## Information

* Server Version: Paper 1.13.2 (With ViaVersion and ProtocolSupport) (compatible to 1.8-1.15)

* OldCombatMechanics version: 1.7.4

* Server Log File: No error log

* OldCombatMechanics config file: Is the default config...

## Problem Description
 When players (in version 1.13.2) do sword-blocking, players in versions prior to 1.9 (1.8) are not able to see players who are in version 1.13.2 when they do sword-blocking. example: if I am playing in version 1.8 and a friend in version 1.13, when he does sword-blocking, he becomes invisible.
Plugins relacionados a todo esto:
OldCombatMechanics
ProtocolSupport
ProtocolSupportStuff
ViaVersion

 
### To Reproduce
1.
2.
3.

**Comment by kernitus** [comment]
This plugin isn't exactly compatible with version < 1.9, for obvious reasons... This is probably because a 1.8 client can't render shields
