### ISSUE TITLE
1.8 armour durability behaviour

### ISSUE THREAD

**Issue by 27chandler** [kernitus/BukkitOldCombatMechanics#387]
## Information

* Server Version: PaperMC 1.15.2

* OldCombatMechanics version: Jenkins Build #2

* Server Log File: https://pastebin.com/asRLLguk

* OldCombatMechanics config file: https://pastebin.com/40W46Z40

## Problem Description

When a player is hit with a weapon with a high damage value (I tested with a sharpness 5 diamond sword) the durability of armour is not reduced by 1 like in Minecraft 1.8 but is instead reduced depending on the damage done (In this case 3 durability points). Unless I have configured the config incorrectly, I believe the old-armour-strength module is not applying. The world this was tested in is called "ServerWorldEnding".

 
### To Reproduce
1. Enable old armor strength in config
2. Log on with two accounts
3. Make account 1 wear normal diamond armour
4. Make account 2 have an enchant diamond sword with sharpness 5
5. Make account 2 hit account 1 once
6. Look at account 1's armour durability in their inventory

### Expected Behaviour
The expected behaviour is that the armour durability should go down by 1 regardless of the weapon strength or type. This was compared to in a 1.7 vanilla server
### Actual Behaviour
Instead the armour goes down in durability depending on the strength of the attack applied.

**Comment by kernitus** [comment]
Is this something that changed from 1.8 to 1.9?

**Comment by 27chandler** [comment]
Yes, a link to the wiki page regarding the changes is written into the comments in the config. (https://minecraft.gamepedia.com/index.php?title=Armor&oldid=909187). In 1.7/1.8 durability changes due to this rule: "Any hit from a damage source that can be blocked by armor will remove one point of durability from each piece of armor worn, except with explosions.The following chart displays how many hits each piece of armor can endure."

But in 1.9 it changes based on the defense points of the armour and the strength of the attack. The old armour durability is following the 1.9 rule instead of the 1.7/1.8 one
