### ISSUE TITLE
Conflict with EpicBosses // Unsafe Enchant

### ISSUE THREAD

**Issue by LavRad** [kernitus/BukkitOldCombatMechanics#388]
## Information

* Server Version: Paper 1.15.2

* OldCombatMechanics version: 1.7.4 and 1.7.5BETA

* OldCombatMechanics config file: https://hasteb.in/afofaziv.yaml

## Problem Description

So when using unsafe (above vanilla) enchants, OldCombatMechanics seems to conflict with EpicBosses' handling of damage dealt making it very hard to kill the boss/entity. This has been reported to EpicBosses, and they've told me to make this report as the issue is with this plugin (you'll see why below).

 
### To Reproduce
1. Setting a Boss to a certain health
2. Applying various sharpnesses both above and below vanilla availability to a sword
3. Recording how many hits/time taken to kill the boss with each sword

### Expected Behaviour
When I tested without OldCombatMechanics, the sharpness 5 sword killed the boss in 7 hits, while the sharpness 10 sword killed the boss in about 4 hits.

### Actual Behaviour

When I tested with it using a sharpness 5 and a sharpness 10 sword. The sharpness 5 sword did the normal high damage you would expect, killing the boss in about 6-7 hits, but the sharpness 10 sword seemed to be doing positive damage most of the time, as the boss gained health somehow instead of losing health.

**Comment by kernitus** [comment]
Should be fixed with b177662
