### ISSUE TITLE
Shield issue (version 1.8.0)

### ISSUE THREAD

**Issue by AggerTV** [kernitus/BukkitOldCombatMechanics#392]
## Information

* Server Version: 
paper-spigot 1.12.2

* OldCombatMechanics version: 
version 1.8.0

* Server Log File: 
https://pastebin.com/KM8LxBHb

* OldCombatMechanics config file: 
https://pastebin.com/9pKSPzuR

## Problem Description

When updating to ocm version 1.8.0 the sword-blocking option just stopped working.
When going back to ocm version 1.7.4 it works again, and blocks shields blocking as intended

 
### To Reproduce
1. update to ocm version 1.8.0

### Expected Behaviour
shield blocking should be dissabled

### Actual Behaviour

shield blocking is not dissabled

**Comment by kernitus** [comment]
I'l be needing a bit more of a description of what exactly should work but doesn't because I don't find this to be the case at all

**Comment by AggerTV** [comment]
Well, shield blocking should be disabled, but no matter if the option in the config.yml is set to true or false, shield blocking is still enabled.

**Comment by kernitus** [comment]
Sorry, but I am unable to reproduce this behaviour.
