### ISSUE TITLE
Conflict with Magic

### ISSUE THREAD

**Issue by Blamo27** [kernitus/BukkitOldCombatMechanics#393]
## Information
* Server Version: 1.15.2

* OldCombatMechanics version: 1.7.5BETA

* OldCombatMechanics configuration: Old-armour-strength enabled

## Problem Description

The module "Old-armour-strength" is causing an issue with the plugin Magic. This plugin applies some damage reductions, for instance when you hold a wand. These damage reductions are normally capped to a certain amount, like maximum 20% damage reduction. This capping doesn't work with OCM's Old Armour Strength, which means players get a 100% damage reduction when 

### To Reproduce

1. Install Magic and OCM latest versions
2. Take in hand a magic wand enchanted with a Protection level 5 (damage_all protection maxed out)
3. You are now invulnerable to damages while holding the wand, even though the maximum damage reduction should be capped to 40%

**Comment by kernitus** [comment]
This seems to work correctly now, probably due to the changes I made for better compatibility with other plugins.
