### ISSUE TITLE
Error with PaperSpigot 1.12.2

### ISSUE THREAD

**Issue by MateoNikolic** [kernitus/BukkitOldCombatMechanics#394]
## Information

* Server Version: PaperSpigot 1.12.2

* OldCombatMechanics version: 1.8.0

* Server Log File: https://hastebin.com/robijataho.rb

* OldCombatMechanics config file: https://hastebin.com/dacoquzugu.bash

**Comment by kernitus** [comment]
@MateoNikolic if you temporarily disable the no projectile randomness module, does the error go away?

**Comment by MateoNikolic** [comment]
No it doesn't

**Comment by kernitus** [comment]
🤔 that's strange...
Also, can you please reupload the logs somewhere else, they disappeared too fast on hastebin!
