### ISSUE TITLE
Disable Water logged blocks

### ISSUE THREAD

**Issue by N0tMyFaultOG** [kernitus/BukkitOldCombatMechanics#397]
## Problem
I'm not sure if this is the right plugin for, but I was looking for an option to disable water logged blocks since they are not a thing in older version but would enhance this plugin a lot if you just """disable"""" this feature.

## Proposed solution
A config option whether to use them or not. That would be a charm.

**Comment by kernitus** [comment]
I'm sorry, but I don't believe this feature has anything to do with combat. It would probably fit better in a different plugin.
