### ISSUE TITLE
Client-sided white name in tab

### ISSUE THREAD

**Issue by fwoompf** [kernitus/BukkitOldCombatMechanics#401]
## Information

* Server Version: Paper-322 (1.15.2)

* OldCombatMechanics version: 1.8.0

* Server Log File: not necessary, there a no error's whatsoever. 

* OldCombatMechanics config file: https://pastebin.com/tRaqPt8w

## Problem Description

Function disable-player-collisions does not works properly. We tested this online with 2 players. But one player that joins when the other is online gets a client-sided white name, while I cannot see this. The config states that it is compatible with scoreboard and tablist-editing plugins, and I am using AnimatedNames by Maximvdw.

 
### To Reproduce
1. set disable-player-collisions to true.
2. Join server with 2+ players
3. On of them gets a client-sided white name.

### Expected Behaviour
No white name should appear.

### Actual Behaviour

What one client sees: https://prnt.sc/sr61ys
What I see: https://prnt.sc/sr62ff

**Comment by SladeHazard** [comment]
i'm pretty sure this is because of viaversion enable auto-team in it and fix-name-colours

**Comment by kernitus** [comment]
@fwoompf Please check if there are any other plugins that try to do the same thing or edit teams significantly, as that would cause a conflict with OCM.

**Comment by Rayzr522** [comment]
closing issue, as user has not replied in over 30 days
