### ISSUE TITLE
FeatherBoard & NameTagEdit reload disconnection

### ISSUE THREAD

**Issue by nick-wd** [kernitus/BukkitOldCombatMechanics#406]
## Information

* Server Version: Paper 1.15.2 (Build 353)

* OldCombatMechanics version: dev build #27

* Server Log File: https://pastebin.com/F2Y1j14N

* OldCombatMechanics config file: https://pastebin.com/NLvSxTz0

## Problem Description

I noticed the other day when a player asked how to turn off the FeatherBoard scoreboard. I told them, /fb toggle. They replied that they got disconnected from the server when this happened. As it turns out, this has been the reason my players have been getting kicked for a while. When doing /FB toggle or /FB Reload, it "disconnects" the players from the server, but doesn't crash the server. I narrowed it down to this plugin specifically. It also effects NameTagEdit (when doing /NTE Reload) it does the same thing and disconnects all of the players. There are no errors in console besides "player has disconnected".

I tested this out on my localhost, and it seemed to work. However, when on my network with waterfall, it has the error occurring. I'm not sure if or how waterfall would affect this, but I don't know any other reason?

 
### To Reproduce
1. Download the latest version of FeatherBoard
2. Setup a bungee network. 
3. Do /FB Reload in-game with OldCombatMechanics installed.
4. Get disconnected with the rest of the players.

### Expected Behaviour
FeatherBoard should just refresh with updated values from the config. 

### Actual Behaviour

FeatherBoard does nothing and then all players are disconnected from the server and sent to the hub.

**Comment by Rayzr522** [comment]
If possible, getting a client log from a user who has been kicked would be helpful. Just the last 20 lines or so from their client log right after they get kicked would do.

You can get these either from going to your Minecraft folder (Options > Resource Packs > Open Resource Pack Folder > go one folder up) and then to the `logs` folder, or by going into advanced settings in the Minecraft launcher and turning the console on. 

Can't imagine how NTE/featherboard sending what I presume are scoreboard team packets would cause a client to be disconnected...

**Comment by nick-wd** [comment]
It's this part of the config: https://pastebin.com/iWXnSg3Q

When enabled is set to true, it crashes. When it's set to false, it's fine.

**Comment by I-Al-Istannen** [comment]
Hey, I can not reproduce this sadly. Featherboard is a paid plugin and I can reload nametagedit just fine :/
Could you share your name tag edit config?

**Comment by nick-wd** [comment]
This seemed to be fixed with turning off player collisions, which is fine, as I want it like that anyway :) 

https://pastebin.com/E194ib3P

**Comment by I-Al-Istannen** [comment]
I have the same config and I can't reproduce it. We have few bug reports like this with various other plugins editing scoreboards but I can't reproduce it so far.

Quite annoying, but I doubt there is much I can do then :/

Thank you though :)
