### ISSUE TITLE
Reload not working in 1.16.1

### ISSUE THREAD

**Issue by spoduminister** [kernitus/BukkitOldCombatMechanics#409]
* Server Version: Spigot 1.16.1

* OldCombatMechanics version: Dev build 27

* Server Log File: https://pastebin.com/NFCtXbWZ 

* OldCombatMechanics config file: https://pastebin.com/y8SuEK7W

## Problem Description

When running the /ocm reload command, the message "An internal error occurred while attempting to perform this command." is sent.
The only other plugins are Multiverse, MV Inventories, and MV Nether Portals. 

EDIT: I tried it without Multiverse, and the same issue happened. If it helps, this was done in a pre-existing world.

**Comment by kernitus** [comment]
Duplicate of #408
