### ISSUE TITLE
Option to disable player attack crits with PaperMC

### ISSUE THREAD

**Issue by GeorgyGasai** [kernitus/BukkitOldCombatMechanics#410]
## Information

* Server Version:  Paper 1.15.2

* OldCombatMechanics version:  latest

* Server Log File:  -

* OldCombatMechanics config file: Any

## Problem Description

Setting disable-player-crits: true in paper.yml stops working when I install your plugin. I ask you to fix this. Thank you in advance.
 
### To Reproduce
1.
2.
3.

**Comment by kernitus** [comment]
What does that setting normally do, and what is it instead doing? That's the purpose of the "expected/actual" behaviour section of the bug report...

**Comment by GeorgyGasai** [comment]
It seemed to me that I wrote extremely clearly. Download the paper core and test it yourself. There is a Disable-player-crits setting in paper.yml. She cuts off critical jumps from weapons. If I install your plugin, then the setup stops working and regardless of true or false, the crits in the jump work

**Comment by I-Al-Istannen** [comment]
Paper integrates these changes directly into the Minecraft entity attack method as seen [here](https://github.com/PaperMC/Paper/blob/36f34f01c09652b3a55008000302114570473953/Spigot-Server-Patches/0197-Toggleable-player-crits-helps-mitigate-hacked-client.patch).
OCM ignores the default damage calculation and applies its own, ignoring that setting ([seen here](https://github.com/kernitus/BukkitOldCombatMechanics/blob/master/src/main/java/kernitus/plugin/OldCombatMechanics/utilities/damage/DamageUtils.java#L34-L38)).

To fix that we could either provide that as an OCM option or detect if the server is running paper and figure out whether that setting is enabled. An OCM toggle would probably be a lot easier and less error prone.

**Comment by AleMastro** [comment]
Hi
there is still a serious problem with the critic (which does not accurately simulate pvp 1.8)
The problem intensified after the addition of "attack-frequency:" (excellent addition) which made the problem more noticeable.
I hope there is an update on this, I do not find any other serious problems like this in the resource.

Thank you so much for your time.
