### ISSUE TITLE
Netherite Weapons wrong damage amount

### ISSUE THREAD

**Issue by DerLinkman** [kernitus/BukkitOldCombatMechanics#412]
Server Version: latest Spigot 1.16.1

No Error Logs.

The weapons don´t behave like they normally would with this plugin.
If you spam klick with them they deal the amount of damage they would do if the cooldown is enabled.

**Comment by kernitus** [comment]
This should now be fixed with commit e97b50a. Please try the [relevant test build](https://ci.rayzr.dev/job/OldCombatMechanics/28/).
