### ISSUE TITLE
Disable enderpearl cooldown module not working

### ISSUE THREAD

**Issue by zacharycram** [kernitus/BukkitOldCombatMechanics#417]
## Information

* Server Version: PaperMC Build 1618 1.12.2

* OldCombatMechanics version:  1.6.6 

* Server Log File: There are no errors.

* OldCombatMechanics config file: https://pastebin.com/wMm9AHE1

## Problem Description

**I want to bring back the old enderpearl in 1.8. In 1.8, enderpearls could be spammed. In 1.9+, it couldn't.
I've tried to enable and disable the enderpearl cooldown feature in the config. Both of them did not work.**

### Expected Behaviour
1. Bring back enderpearl spamming
### Actual Behaviour

Nothing happens. The enderpearl still has a cooldown delay before being able to use it.

**Comment by kernitus** [comment]
This is what the `disable-enderpearl-cooldown` module does. Did you reload the plugin after enabling the module?

What is the exact behaviour when you try to use enderpearls (cooldown time, animation)?

**Comment by zacharycram** [comment]
Yes i did reload it, the behaviour of the enderpeatl cooldown didnt get removed, and as for the animation i dont really know what you're talking about

**Comment by kernitus** [comment]
There should be an animation in the hotbar to show the cooldown, after you launch an enderpearl

**Comment by zacharycram** [comment]
The animation does play, regardless of the settings

**Comment by kernitus** [comment]
Can I please ask you to enabled  `debug` in the config and try launching some enderpearls, and check if there is any relevant debug output?
