### ISSUE TITLE
Separate cooldown for each golden apple type

### ISSUE THREAD

**Issue by Momonche** [kernitus/BukkitOldCombatMechanics#420]
## Problem
Actually, it's impossible to have a cooldown for GOLDEN_APPLE and another for ENCHANTED_GOLDEN_APPLE

## Proposed solution
Make a cooldown for GOLDEN_APPLE and another for ENCHANTED_GOLDEN_APPLE

**Comment by I-Al-Istannen** [comment]
Do you want them to *share* a cooldown? Or should you be able to eat an enchanted apple and right in the next second eat a normal one?

**Eat a normal apple, then**
- eat a normal apple ==> Normal apple cooldown applies
- eat an enchanted apple ==> Normal apple cooldown applies

**Eat an enchanted apple, then**
- eat a normal apple ==> Enchanted apple cooldown applies
- eat an enchanted apple ==> Enchanted apple cooldown applies

Or rather

**Eat a normal apple, then**
- eat a normal apple ==> Normal apple cooldown applies
- eat an enchanted apple ==> No cooldown applies

**Eat an enchanted apple, then**
- eat a normal apple ==> No cooldown applies
- eat an enchanted apple ==> Enchanted apple cooldown applies

**Comment by Momonche** [comment]
Eat an enchanted apple, then

eat a normal apple ==> No cooldown applies
eat an enchanted apple ==> Enchanted apple cooldown applies

That's what I want to do
