### ISSUE TITLE
There is a big error when a player hits another player

### ISSUE THREAD

**Issue by PrimePvP** [kernitus/BukkitOldCombatMechanics#421]
Information
Server Version: Spigot 1.12.2

OldCombatMechanics version: 1.8.0

OldCombatMechanics config file: default

Problem Description
When a player hits another player the console displays this error: https://pastebin.com/ahgiPvsx

**Comment by kernitus** [comment]
Also, you stated you're using version 1.8.0 when from the log it is clear you're not.
