### ISSUE TITLE
Offhand armor duplication

### ISSUE THREAD

**Issue by dryter97** [kernitus/BukkitOldCombatMechanics#423]
server version: 1.14.4 paper(243)
* OldCombatMechanics version: 1.7.4 1.8.0 and 1.8.1
* Server Log File: no logs concerning old combact mechanics
* OldCombatMechanics config file: [click here for a google drive files](https://drive.google.com/file/d/1SMj2g2yDqduv7Lao5xKxWQH3ol5DJaPS/view?usp=sharing)

Issus is related to offhand armor duplication or all items could be equip into any armor slot.

1. take a armor item into your offhand and a sword (melee weapon) into your main hand
2. try to shield using the old combat mecanics fake shield will replace your offhand items
3. your armor was in your offhand will be equip before the shield replace it. when you stop shielding it will bring back a copy of your armor in same time its dupping it.

what is suposed to perform is not dupping it by not trying to copy armor item but i can understand forcing a copy of the item. i think by working a bit offhand replacement ticks would help a bit.

im prety sure other version than 1.14 are concern too

There is a short gif files showing you the exemple stored on my dedicated server
[https://idryt.pandacrafts.ca/20200711073550.gif](https://idryt.pandacrafts.ca/20200711073550.gif)

**Comment by kernitus** [comment]
I'm assuming you have the disable-offhand module disabled? I can't actually see your config file, it says access is denied.

**Comment by I-Al-Istannen** [comment]
@dryter97 I can reproduce the *visual effect*. But when I try to click on the equipped boots, they just disappear. The item is only duped on the client apparently.

**Comment by kernitus** [comment]
Actually yes, I managed to get the same effect with a shield. But as soon as you try the item, it disappears.

**Comment by dryter97** [comment]
For my part I thought it was client side but it was server side too I'll
try to reproduce it maybe caused by the actual version I'm using of the
spigot himself
