### ISSUE TITLE
Attack Cooldown not being disabled.

### ISSUE THREAD

**Issue by Blaster76606** [kernitus/BukkitOldCombatMechanics#425]
## Information

* Server Version: 
Spigot 1.16.1

* OldCombatMechanics version: 
Version 1.81

* Server Log File: 
[Sun, 19. Jul 2020 02:04:08 GMT WARN] [OldCombatMechanics] Error reloading module 'Disable Attack Cooldown' 
(Its just one line so I figured this would be fine)

* OldCombatMechanics config file: 
https://pastebin.com/JxUtytxx
## Problem Description

Even on server start Attack cooldowns don't get disabled and when reloaded it starts it can't reload the Disable Attack Cooldown module. There is no errors that display when the server starts up.
 
### To Reproduce
1.
2.
3.

### Expected Behaviour
Disabled Attack Cooldown.
### Actual Behaviour

Not disabled.

**Comment by Rayzr522** [comment]
@Blaster76606 a full log file would very much be appreciated

**Comment by Blaster76606** [comment]
[latest(1).log](https://github.com/kernitus/BukkitOldCombatMechanics/files/4943171/latest.1.log)

**Comment by Rayzr522** [comment]
<details>
<summary>click to view extracted plugin list</summary>
<pre>
AdvancedAchievements
AntiAFKPro
BeastWithdraw
BetterBeacons
Chairs
ChestShop
Clans
CoreProtect
DiscordSRV
DragonSlayer
EnchantPlus
Essentials
EssentialsChat
EssentialsSpawn
FastLeafDecay
FogusCore
GoldenCrates
GriefPrevention
GriefPreventionFlags
HolographicDisplays
HsRails
InventoryRollback
LibsDisguises
LuckPerms
Minepacks
MobArena
Morphy
MovingDevApi
Multiverse-Core
Multiverse-Inventories
Multiverse-NetherPortals
Multiverse-Portals
MyCommand
MythicMobs
OldCombatMechanics
OpenInv
PlaceholderAPI
PlaceItemsOnGroundRebuilt
PlotSquared
Plugin
ProtocolLib
PvPToggle
RewardPRO
SellStick
sleep-most
Vault
VeinMiner
VillagerOptimiser
Wild
WorldEdit
WorldGuard
</pre>
</details>

based on your plugins, i don't see anything that could be causing this error. however, i see the line of code that's at fault, and I have a possible patch available in [dev build 38](https://ci.rayzr.dev/job/OldCombatMechanics/38/)

@Blaster76606 please try this out and let me know if it solves your issue

**Comment by Rayzr522** [comment]
oh yeah @Blaster76606 do you have any player spoofing or NPC plugins? I didn't see anything like Citizens in there, and I'm pretty sure Citizens is fine with OCM, but I'm thinking this might've been caused by fake player entities. do any of your plugins create fake player entities?

**Comment by Blaster76606** [comment]
The Dev build did remove the error message but It still didn't disable the combat cooldown. 
I do NOT have any plugins create Fake player entities. The only plugin that that that might have been able to was Morph and its required plugin Lib's Disguises so I tried removing them but still doesn't work.

**Comment by Rayzr522** [comment]
this has to be caused by some kind of weird plugin incompatibility. @Blaster76606 please try removing plugins until this issue goes away, so we can identify what plugin is causing a conflict here. i'm unable to reproduce this issue, and nothing in the log file hints at why this would be happening.
