### ISSUE TITLE
Manually adding sword/armor items

### ISSUE THREAD

**Issue by PokeHub** [kernitus/BukkitOldCombatMechanics#428]
It seems that Modded items are not supported. Although it would be impossible to add ALL modded items and give them 1.8 combat mechanics, being able to manually add things like `Pixelmon_moon_stone_sword` to the config as a sword item would be amazing, and I think would solve that problem. As Mohist (a forge/sponge bridge) is just starting to become a popular alternative to SpongeForge, I assume more and more people will be interested in these modded item additions.

**Comment by PokeHub** [comment]
Going through the config again, I'm trying adding

**Comment by Rayzr522** [comment]
@PokeHub i'm actually kinda curious how you were able to solve this. while we don't really support modded Minecraft since there isn't a standard, stable, mature ecosystem for forge + bukkit (yet), i'm interested in how you were able to solve this with Mohist

**Comment by PokeHub** [comment]
So I've had some. (a LOT) of issues. I'll be posting a new ticket in a moment!
