### ISSUE TITLE
Netty Thread lag with sword sweep module

### ISSUE THREAD

**Issue by BrodyBeckwith** [kernitus/BukkitOldCombatMechanics#429]
## Information

* Server Version: Tuinity 1.15.2

* OldCombatMechanics version: Jenkins Build #39

* Server Log File: Unrelated
Spark: 
![firefox_xSJ99rcpuG](https://user-images.githubusercontent.com/29649887/88006459-aac56a80-cad9-11ea-9eaa-d17308b66c0f.png)
![firefox_WUrT8UJe2P](https://user-images.githubusercontent.com/29649887/88006539-dea09000-cad9-11ea-9bb7-9a58eb88602d.png)
![firefox_W6n7xjVFsv](https://user-images.githubusercontent.com/29649887/88006511-ca5c9300-cad9-11ea-8e34-86dbe1f156bb.png)

* OldCombatMechanics config file: Defaults

## Problem Description

When the server has around 150+ players the server becomes unplayable and it appears the issue is the Netty threads are completely taken up by oldcombatmechanics and what seems it working on the sweeping edge packet.

 
### To Reproduce
1. ~150-200ish players online

**Comment by Rayzr522** [comment]
@I-Al-Istannen any idea why the init for SweepPacketDetectorFrom1_13 would be taking up so much time? shouldn't it just be happening once and then never again??

**Comment by I-Al-Istannen** [comment]
Yes and sadly no.

**Comment by kernitus** [comment]
@BrodyBeckwith Please try [test build 40](https://ci.rayzr.dev/job/OldCombatMechanics/40/).

**Comment by BrodyBeckwith** [comment]
> 
> 
> @BrodyBeckwith Please try [test build 40](https://ci.rayzr.dev/job/OldCombatMechanics/40/).

Not going to be able to test this with a lot of players for awhile but I will let you know when I do.
