### ISSUE TITLE
Players disconnect when killed and when you kill.

### ISSUE THREAD

**Issue by Furry** [kernitus/BukkitOldCombatMechanics#432]
## Information
* Server Version: Paper 1.16.1

* OldCombatMechanics version: 1.8.1

* Server Log File: N/A

* OldCombatMechanics config file: 
[config.txt](https://github.com/kernitus/BukkitOldCombatMechanics/files/4956049/config.txt)

## Problem Description
When a player kills another one in my Kit-PvP server, both players immediately disconnect and are sent back to the hub server. There's no message in log when this happens, and no errors/information provided about the event.

### To Reproduce
1. Have one player kill another

### Expected Behaviour
The players would respawn at the kitpvp arena spawn, but instead, they just disconnect. 
### Actual Behaviour
The moment one player dies, both players involved in the combat instantly disconnect, and are sent back to the lobby with "You have been moved to the fallback server" in chat. 
![9HCzMhS](https://user-images.githubusercontent.com/22103494/88104131-fcb8cf80-cb6f-11ea-96a1-096bc269d896.png)

**Comment by Rayzr522** [comment]
> Server Log File: N/A

incorrect, log files are critical when debugging. please provide one, otherwise all we have to go off is the screenshot you sent, which says nothing other than that they were kicked.
