### ISSUE TITLE
Fishing rod knockback works in PvP Deny worldguard regions

### ISSUE THREAD

**Issue by itsWarHammer** [kernitus/BukkitOldCombatMechanics#433]
- Ver : Paper-1618 mc: 1.12.2

- OCM 1.8.1

- https://pastebin.com/QtxcZqJW

**Comment by kernitus** [comment]
Sorry, I'll be needing a lot more detail than that to be able to do anything about this. Also if those are two separate issues, they should be reported as such

**Comment by itsWarHammer** [comment]
What more detail do you require ?

**Comment by kernitus** [comment]
The exact steps to replicate the behaviour you believe as wrong, and what you think it should be doing instead.

**Comment by itsWarHammer** [comment]
as said in your config 

  # This is to cancel dragging in the entity attached to the fishing rod when reeling in, like in 1.8
  # Options: all, players, mobs, none. players allows compatibility with WorldGuard pvp-deny regions
  cancelDraggingIn: players

Players can knock players with their fishing rod outside of spawn (pvp = deny) and kill them while afk 

Here is a video of the issue
https://youtu.be/xIDfXyiSmfw

**Comment by kernitus** [comment]
Are both players in a WorldGuard region that denies pvp?

**Comment by itsWarHammer** [comment]
Yes

**Comment by Rayzr522** [comment]
i'm simplifying this issue report to just the worldguard PVP stuff, however @itsWarHammer please feel free to open a separate issue with more details about the fishing rod knockback and jumping bug. (may be related to #400?)

I'm unable to reproduce the pvp issue as long as `checkCancelled` is `true` in the config. please follow the issue template when reporting and provide your OCM config so we can attempt to reproduce

**Comment by itsWarHammer** [comment]
https://pastebin.com/QtxcZqJW < My config, ive already given it to you from the start of this issue

**Comment by Rayzr522** [comment]
I see, my apologies, I missed that. using your config and the following versions:
```
> version
[13:23:01 INFO]: This server is running Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[13:23:01 INFO]: Previous version: git-Tuinity-"475ca7c" (MC: 1.16.1)
[13:23:01 INFO]: You are running the latest version
> version WorldEdit
[13:23:14 INFO]: WorldEdit version 6.1.9;caf0ad9
> version WorldGuard
[13:23:16 INFO]: WorldGuard version 6.2.2-SNAPSHOT;8eeab68
> version OldCombatMechanics
[13:23:18 INFO]: OldCombatMechanics version 1.8.1
[13:23:18 INFO]: Reverts to pre-1.9 combat mechanics
[13:23:18 INFO]: Website: https://github.com/kernitus/BukkitOldCombatMechanics
[13:23:18 INFO]: Authors: kernitus and Rayzr522
>
```
i was unable to reproduce the issue. all I did was create a region named `spawn1`, set `pvp` to `deny` (which can be confirmed in that punching the player resulted in the regular pvp is not allowed message)

could you provide a plugin list, as well as attempt to reproduce this with a minimum setup with just Spigot, OCM, WorldEdit, and WorldGuard?

**Comment by itsWarHammer** [comment]
fixed
