### ISSUE TITLE
Console Error and Plugin disable

### ISSUE THREAD

**Issue by SaveStandard** [kernitus/BukkitOldCombatMechanics#436]
Server Version: 1.14.4

OldCombatMechanics version: Jenkins dev #40

Server Log File: https://pastebin.com/prT6cjX1

OldCombatMechanics config file: https://pastebin.com/DbVfXJr1

**Comment by Rayzr522** [comment]
duplicate of #437, see [this comment](https://github.com/kernitus/BukkitOldCombatMechanics/issues/437#issuecomment-669449688) for a dev build that should fix the error
