### ISSUE TITLE
PlaceholderAPI - OCM

### ISSUE THREAD

**Issue by nick-wd** [kernitus/BukkitOldCombatMechanics#437]
## Information

* Server Version: Tuinity 1.16.1

* OldCombatMechanics version: 1.8.1

* Server Log File: https://pastebin.com/FUVYEfcc

* OldCombatMechanics config file: https://pastebin.com/ZNmssKWZ

## Problem Description

Won't load with the new PAPI update.

 
### To Reproduce
1. Download new PAPI
2. Download OCM
3. Start server

### Expected Behaviour
Should load.

### Actual Behaviour

Doesn't load.

**Comment by Ansandr** [comment]
This went by itself with the release of the new version PAPI (2.10.9)

At least that's the way for me

**Comment by Rayzr522** [comment]
@nick-wd can you confirm the PlaceholdeAPI version you had where this was an issue?

**Comment by Rayzr522** [comment]
```
[13:56:37 WARN]: [PlaceholderAPI] ocm is attempting to register placeholders via a PlaceholderHook class which is no longer supported!
```

Here is the root cause, looks like I'll need to rewrite PAPI support with OCM to use the new PlaceholderExpansion system rather than the (now long deprecated) PlaceholderHook.

I'm surprised this hasn't been an issue sooner, I'll write up a patch for it lol

**Comment by Rayzr522** [comment]
@nick-wd and @Ansandr if you could both confirm with latest PlaceholderAPI that dev build 41 works and that `/papi parse me %ocm_pvp_mode%` shows a valid value (and not just the placeholder itself), that would be much appreciated: https://ci.rayzr.dev/job/OldCombatMechanics/41/

**Comment by SladeHazard** [comment]
? this is because ur using old methods of placeholderapi they got a big update.

**Comment by Rayzr522** [comment]
yep, I'm aware of that and have patched it in the dev version @SladeHazard. just was awaiting testing from the original reporter but I'm pretty confident this is fixed regardless
