### ISSUE TITLE
AXES BROKEN! CRITICAL damage same

### ISSUE THREAD

**Issue by SladeHazard** [kernitus/BukkitOldCombatMechanics#440]
Axes are broken as you can see in this video: https://www.youtube.com/watch?v=GwQFf7n74ds critical does 3 hearts of damage and normal hit does 3 too?????! WHAT!

**Comment by Rayzr522** [comment]
a video is of very little use, please turn debug mode on in the OCM config and show actual numbers being printed out in chat. it will provide us with far more valuable information to determine what's going on
