### ISSUE TITLE
Can't eat golden apples

### ISSUE THREAD

**Issue by PrimePvP** [kernitus/BukkitOldCombatMechanics#447]
Server Version: PaperSpigot 1.12.2
OldCombatMechanics version: 1.8.1
OldCombatMechanics config file: https://pastebin.com/JVLXhMbF

Description: 
When you get hit and try to eat the apple it can't be eaten.

**Comment by PrimePvP** [comment]
When a player hits another player, the player that gets the hit try to eat a golden apple but he can't because of this bug.

**Comment by kernitus** [comment]
Does this happen with any other food items?

**Comment by awgybop1** [comment]
Same issue here, only Golden Apples. Disabling/removing the plugin fixes the issues. Gapples can also get stuck in an endless loop where they keep subtracting from your inventory when you're not eating them anymore.
This is on a PaperSpigot 1.16.3 server, and this bug seems to only occur on versions lower than 1.16 (using ViaBackwards and ViaRewind for old protocol support.)

**Comment by kernitus** [comment]
@awgybop1 Does only disabling the gapples module prevent the issue?

**Comment by awgybop1** [comment]
@kernitus At this moment I am no longer experiencing this issue for some reason. I am now running PaperSpigot 1.16.4 (not sure if it made the difference) and have updated several plugins such since aswell.

So as of this moment, this issue no-longer occurs - but I am unsure why that is.

**Comment by kernitus** [comment]
We shall reopen this if the issue comes up again. Hopefully with a more detailed description too :wink:

**Comment by awgybop1** [comment]
I have disabled the Old Golden Apples in the config aswell, still did this. I might just manually take it out of the plugin and just write my own system as this is very annoying, but I like every other the feature the plugin has. 
Sometimes when you eat the Notch Apples (Not sure about normal Golden Apples), they will just keep subtracting from your inventory as if you kept holding the button, but you can see from this videos that I am not consuming them.

https://gyazo.com/fddccafcda9b0a22e52a54ccdc9d4111
