### ISSUE TITLE
/ocm toggle not working

### ISSUE THREAD

**Issue by MinecraftAdmin** [kernitus/BukkitOldCombatMechanics#448]
Running OCM 1.8.1 (from Spigot) on Paper 1.16.1

On 1.8.1, `/ocm toggle` does not do anything. It does not toggle the cooldowns, and does not show any error messages. Nothing is posted in console either.

1.8.0 did not have this issue for me.

/ocm shows proper plugin info, so its not a command conflict.

**Comment by I-Al-Istannen** [comment]
Which cooldowns exactly?

**Comment by MinecraftAdmin** [comment]
> Which cooldowns exactly?

The 1.8/1.9 pvp cooldowns.

**Comment by kernitus** [comment]
I think we should retire `/ocm toggle` for it has outlived its usefulness and it doesn't do what people expect. It made sense when the plugin only modified attack speed, but now it does much more than that and ends up with unbalanced combat otherwise. Something like on #179 would make more sense.

**Comment by kernitus** [comment]
You must turn on `enableIndividualToggle` in the config for the toggle command to work.
