### ISSUE TITLE
Negative attack damage

### ISSUE THREAD

**Issue by SladeHazard** [kernitus/BukkitOldCombatMechanics#449]
* Server Version: 1.12.2 Paper

* OldCombatMechanics version: 1.8.1BETA 

* Server Log File: https://pastebin.com/m0mz0ByV

* OldCombatMechanics config file: https://pastebin.com/9z4NaJSF

Sometimes axes randomly don't do damage for players? this is very annoying

 
This happens randomly so I don't know how to reproduce there is a video below

1. I think it happens mostly if you use strength

### Expected Behaviour
For the axe to do normal damage according to the config

### Actual Behaviour
the axe does 0 damage

Video: https://youtu.be/WgavIv_kLNs
Skip to 0:33 to watch it happen. please fix this my server is literally ruined cuz of it

**Comment by SladeHazard** [comment]
the axe that was being used has following enchants: sharp 85, unb 85 , fireaspect 2!

**Comment by SladeHazard** [comment]
happens without strength ASWELL watch this video in slowmo skip to 0:24 : https://www.youtube.com/watch?v=1fYUmO3tRVs&feature=youtu.be

**Comment by SladeHazard** [comment]
i swear ive tried every old oldcombatmechanics version aswell as ever config possible ;/ randomly axes deal less dmg any fix? or way to prevent this please!

**Comment by kernitus** [comment]
Are you sure you aren't simply attacking too fast? Even though there is no weapon cooldown, Minecraft still has a damage cooldown (since before 1.9).

**Comment by SladeHazard** [comment]
> Are you sure you aren't simply attacking too fast? Even though there is no weapon cooldown, Minecraft still has a damage cooldown (since before 1.9).

I'm not, only 2-4cps

**Comment by kernitus** [comment]
I don't find this to be the case when I load up a server to test it, is there some specific situation in which this happens that I can try to reproduce?

**Comment by SladeHazard** [comment]
uh it turns it they were your bad coded old plugin vers.......... that corrupted my whole servers items every old armor from old oldcombatmechanics versions have 9999+armor toughness the new plugin doesn't overwrite it.

**Comment by Rayzr522** [comment]
@SladeHazard you could try installing [OCMFixer](https://github.com/Rayzr522/OCMFixer) and see if that helps; running the /read command isn't actually what you want, but rather just leaving it installed for a bit and letting the ArmorFixListener do its thing. it cleans any armor in either player inventories or container inventories every time a player joins / an inventory is opened

**Comment by SladeHazard** [comment]
alright thanks, you can close this now. I had already coded my own plugin to remove the attributes
