### ISSUE TITLE
Switch weapon cause multiple damage

### ISSUE THREAD

**Issue by variationtime** [kernitus/BukkitOldCombatMechanics#450]
* Server Version:  1.12
* OldCombatMechanics version: 1.8.1
* Server Log File: no error
* OldCombatMechanics config file:  https://pastebin.com/GNrpwxxD

## Problem Description
Every time you quickly change weapons in your hotbar slots, the damage goes from each of them. That is, there is no delay in dealing damage. Let's say a player hits with only 1 sword, he damage 15 hearts in 5 seconds. but if at the same time he will change his weapons very quickly and beat with both, then he will take 15 hearts in 3 seconds.

1. get sword
2. get another weapon. like pickaxe
3. start switching them like a hacker and attack enemy at the same time = u deal x2 damage

add me in discord, i will show vid if u need Variation#1111

**Comment by kernitus** [comment]
Yes, and damage cooldown is still very much a thing, the plugin doesn't change that.
