### ISSUE TITLE
Thorns causing too much damage

### ISSUE THREAD

**Issue by TheEndless7** [kernitus/BukkitOldCombatMechanics#455]
* Server Version: 1.15.2

* OldCombatMechanics version: 1.8.1

* Server Log File: https://gist.github.com/TheEndless7/aa7d76577b9c3f0aebe90bc43ef111c5

* OldCombatMechanics config file: https://gist.github.com/TheEndless7/aa7d76577b9c3f0aebe90bc43ef111c5

* Problem Description
Thorns 3 deals way too much damage (6-10 hearts) when the person is hit if said person using thorns 3 is holding a sharpness 5 sword. Disabling old-tool-damage fixes the problem but I want to also use the setting.

### To Reproduce
1. Wear full thorns 3 diamond gear
2. Hold a sharpness 5 diamond sword
3. Have someone hit you and watch them take 6-10 hearts of damage if they don't have armor from full health

### Expected Behaviour
Person loses 1-4 hearts upon hitting user with thorns 3

### Actual Behaviour
Person loses around 6-10 hearts upon hitting user with thorns 3

### Video
https://youtu.be/yIY6AXKYHTU

**Comment by TheEndless7** [comment]
Here's another video if it helps!
https://drive.google.com/file/d/1NTasn16q9cWtKkdZX-GSEZcc6GP09e6L/view

**Comment by 27chandler** [comment]
I can confirm I am also getting this bug on my server (1.16.3). I did some testing and we found that when person A attacks person B, if person B has thorns on then person A recieves the damage from the item person B is holding.

So if B has a sharpness 5 diamond sword and gets hit, A will recieve the equivalent of if they got attacked with the sword.

**Comment by johnyuki** [comment]
Can confirm this issue also is present on our server. This should really be fixed as the issue has been open for a while now.
