### ISSUE TITLE
Netherite damage output

### ISSUE THREAD

**Issue by Sfekke** [kernitus/BukkitOldCombatMechanics#463]
## Information

* Server Version: Spigot 1.16.3

* OldCombatMechanics version: Release 1.8.1

* Server Log File: [latest.log](https://pastebin.com/jHpaVCFn)

* OldCombatMechanics config file: [Config.YML](https://pastebin.com/XAEGYuKW)

## Problem Description

Netherite Sword is way below what it should be.
It seems like it's even less powerful than killing mobs by hand?
Even tropical fish (which should be one hit kills) take 2-3 hits.
 
### To Reproduce
1. Spawn a tropical fish (Or any other mob)
2. Try to kill it with a Netherite sword
3. Always end up needing 2-3 hits

### Expected Behaviour
The item (Netherite Sword) should output enough damage to kill mobs faster than bare hands.
### Actual Behaviour

Netherite Sword is immensely underpowered & on par with stone/wooden tools

[Took me a minute to find some time, here's a video showing the problem occurring under different scenarios.](https://youtu.be/pm2aOKpxgJE)

**Comment by kernitus** [comment]
You don't have the netherite tools in your config, of course it's not going to work properly! The config has been updated to include those, if you regenerate it you'll see the values added there.

**Comment by Sfekke** [comment]
That explains a lot!
I'm sorry for not having tried that, totally slipped my mind.

Thanks for the reply =)
