### ISSUE TITLE
ERROR Could not pass event EntityRegainHealthEvent to OldCombatMechanics v1.8.1

### ISSUE THREAD

**Issue by EEmperor02** [kernitus/BukkitOldCombatMechanics#467]
* Server Version: 1.16.3

* OldCombatMechanics version:  1.8.1v

* Server Log File: https://pastebin.com/7MDeJmTn

* OldCombatMechanics config file: https://pastebin.com/6L5ZRiiH

## Problem Description
I got spam in console

**Comment by kernitus** [comment]
Are you perhaps using spartan anticheat?
