### ISSUE TITLE
Disabling netherite armor's knockback resistance.

### ISSUE THREAD

**Issue by Agaloth** [kernitus/BukkitOldCombatMechanics#469]
As the title says, being able to disable netherite armor's knockback resistance.

Why? Because Netherite's knockback resistance breaks PvP in a way that combos are not too good.

Exemple:

```
disable-knockback-resistance:
  # Disables netherite armor's knockback resistance.
  enabled: true
```

**Comment by kernitus** [comment]
I believe the only way to 'fix' this would be to recalculate the knockback entirely, so it could only be done if #391 is also fixed.
