### ISSUE TITLE
1.8 Knockback

### ISSUE THREAD

**Issue by Xd-pro** [kernitus/BukkitOldCombatMechanics#470]
## Problem
I am not dealing the correct amount of sprint-hit (w/s tap) knockback and the vertical knockback is too low. In 1.8/1.7 The knockback deals lots of vertical and lots of horizontal if you are sprint-hitting or w/s tapping

## Proposed solution
Add some "modifiers to fix the 1.9+ knockback

**Comment by NOR7BE** [comment]
Really useful suggestion.

**Comment by kernitus** [comment]
Duplicate of #391
