### ISSUE TITLE
Blocking not visible from 1.8 with ProtocolSupport

### ISSUE THREAD

**Issue by arceuss** [kernitus/BukkitOldCombatMechanics#473]
![image](https://user-images.githubusercontent.com/28229451/99848469-132f6180-2b37-11eb-9000-3e6d57156ec5.png)
using latest paper and protocolsupport

**Comment by kernitus** [comment]
Sorry but I haven't a clue what sort of wacky stuff ProtocolSupport, ViaVersion, ViaBackwards etc. do to work. They often conflict with OCM because it was never intended to work with 1.8 clients. Maybe at some point in the future I will have the time to investigate this.

**Comment by codergautam** [comment]
f

**Comment by pabloalba16** [comment]
You can bring up 1.8 sword blocking on protocolsupport with this plugin: https://www.spigotmc.org/resources/protocolsupportstuff.44527/

**Comment by kernitus** [comment]
@pabloalba16 That looks doable, it seems that plugin [modifies some packets ](https://github.com/PerfectDreams/ProtocolSupportStuff/blob/master/src/main/kotlin/net/perfectdreams/protocolsupportstuff/hacks/SwordBlockingHack.kt) for certain clients so that 1.8 clients see people blocking. It should be possible to integrate that into OCM.

**Comment by pabloalba16** [comment]
that would be amazing! thank you so much!

**Comment by NotAlexNoyle** [comment]
> @pabloalba16 That looks doable, it seems that plugin [modifies some packets ](https://github.com/PerfectDreams/ProtocolSupportStuff/blob/master/src/main/kotlin/net/perfectdreams/protocolsupportstuff/hacks/SwordBlockingHack.kt) for certain clients so that 1.8 clients see people blocking. It should be possible to integrate that into OCM.

I am experiencing a similar issue, players on 1.8 clients cant see people drawing back their bows to shoot. This also occasionally causes the player to become invisible. Would it be possible to integrate a similar packet fix for bows as you are planning to do for sword blocking here? Thanks!

**Comment by kernitus** [comment]
@NotAlexNoyle That doesn't sound like OCM is the cause of that problem, so it would not be possible to fix that from this plugin.

**Comment by pabloalba16** [comment]
@NotAlexNoyle Are you using ProtocolSupport or ViaRewind to bring back 1.8 support?

**Comment by NotAlexNoyle** [comment]
> @NotAlexNoyle Are you using ProtocolSupport or ViaRewind to bring back 1.8 support?

ViaRewind. Would I be correct in assuming that this issue is applicable for ViaRewindLegacySupport?

**Comment by pabloalba16** [comment]
ViaRewindLegacySupport does not claim to fix it in their spigot description. If players become invisible, that's ViaRewind issue. It does not seems like they haven't implemented the draw back for bows. ProtocolSupport has it but it is discontinued and incompatible with some anticheats so it is not viable

**Comment by pabloalba16** [comment]
https://github.com/ViaVersion/ViaRewind/issues/64

**Comment by kernitus** [comment]
This is actually not OCM's responsibility. All OCM does is give the player a shield. If ViaRewing/ViaBackwards etc. are able to show a 1.8 client who is sword-blocking as holding a shield, then they should also be able to show a 1.9+ client who is shield-blocking as sword-blocking. If that is not currently the case, that is a feature request for those plugins.
