### ISSUE TITLE
Disable attack cooldown per-world not working

### ISSUE THREAD

**Issue by Sparxez** [kernitus/BukkitOldCombatMechanics#475]
## Information

* Server Version: 1.16.4

* OldCombatMechanics version: 1.8.1

* OldCombatMechanics config file: https://pastebin.com/5QR1rRre

## Problem Description
I have used the config to make disable attack cooldown for only the 'kitpvp' world but it seems to work in all worlds. I restarted the server and used /ocm reload.

**Comment by kernitus** [comment]
Yeah uuh it works fine here, are you sure that's the name of the world, and that it reloaded properly? Are there any errors in the console?
