### ISSUE TITLE
Toggleable individual weapon cooldown

### ISSUE THREAD

**Issue by CrunchyDp** [kernitus/BukkitOldCombatMechanics#476]
## Problem
I would like to make axes still have the new pvp mechanics
## Proposed solution
Add an option in the config for both weapons

Example:
disable-attack-cooldown:
   This is to disable the attack cooldown
  enabled: true
  worlds: []
   What to set the attack speed to. Default for 1.9 is 4, at least 16 is needed for no cooldown.
  generic-attack-speed: 24
  adds an exception to this rule
 axe-exception-enabled: true
 sword-exception-enabled: false

**Comment by kernitus** [comment]
This is not possible because the cooldown is a player attribute, and not a per-tool attribute.
