### ISSUE TITLE
Rods are still pulling instead of making things take knockback

### ISSUE THREAD

**Issue by Aarielegend** [kernitus/BukkitOldCombatMechanics#478]
## Information

* Server Version: 1.16.4

* OldCombatMechanics version: 

* Server Log File: 

* OldCombatMechanics config file: 

### To Reproduce
1. Have this plugin installed
2. Use your rod on an entity
3. It doesn't give kb

**Comment by kernitus** [comment]
This just depends on how you configured the `old-fishing-knockback` module, but you didn't post your config...
