### ISSUE TITLE
Totem of undying doesn't work when blocking

### ISSUE THREAD

**Issue by Titaniumtown** [kernitus/BukkitOldCombatMechanics#479]
## Information

* Server Version:  1.16.4

* OldCombatMechanics version: 1.8.1

## Problem Description
When you're blocking your sword and die, your totem of undying in your off hand doesn't work.

### To Reproduce
1. Block with sword with totem in your off hand
2. Fall to your death

### Expected Behaviour
Totem should activate.

### Actual Behaviour
You die

**Comment by kernitus** [comment]
Well yeah, cause it's no longer in your offhand if you're blocking...
