### ISSUE TITLE
¿BOW BOSTING LIKE 1.8/1.12?

### ISSUE THREAD

**Issue by alexeses** [kernitus/BukkitOldCombatMechanics#485]
Hello!

I am a faithful follower of OldCombatMechanics, it brings incredible features. However, when you can implement the PUNCH with the bow bosting called better. 

I have 80% of my servers in the new version of minecraft 1.16 and apparently users can't use it. 

For the pvp is something fundamental, do you think it could be implemented? I would be very grateful!

Thanks for all the work you do!

Alex.

**Comment by kernitus** [comment]
I can't exactly tell what you're looking for, but there is already a module designed to disable bow boosting. That's all it does, because OCM is supposed to replicate 1.8 combat.
