### ISSUE TITLE
Attack Sound still there

### ISSUE THREAD

**Issue by Nickuuss** [kernitus/BukkitOldCombatMechanics#486]
Hi, I'm using a 1.16.3 Bukkit Server and the newest Version of this plugin but when i join on the Server and attack a mob there is still this annoying attack sound.

**Comment by kernitus** [comment]
What attack sound are we talking about here?

**Comment by Nickuuss** [comment]
the one that appears when you swing the sword for example and when i spam the left mouse it appears all the time

**Comment by kernitus** [comment]
Do you mean the sweep attack?
