### ISSUE TITLE
Make crouching hitbox change configurable

### ISSUE THREAD

**Issue by sethwheway** [kernitus/BukkitOldCombatMechanics#489]
## Problem
As you know, in later versions, crouching changes the players' hitbox and eyeheight. This ruins bridging muscle memory and makes certain types of bridging much more difficult

## Solution
A config option to toggle this on or off

**Comment by kernitus** [comment]
This, if implemented, should be done so together with #69

**Comment by MWHunter** [comment]
This isn't possible.  The client predicts the block place result client-sided before the server processes the block place.  Unless you are modifying the client too, you will just desync both the client and server.

**Comment by sethwheway** [comment]
This is a shame. Thank you for the consideration
