### ISSUE TITLE
Fishing rod knockback in WorldGuard regions

### ISSUE THREAD

**Issue by martijnpu** [kernitus/BukkitOldCombatMechanics#490]
## Information
* Server Version: Paper 1.16.5

* OldCombatMechanics version: 1.9.0

* Server Log File: Not needed

* OldCombatMechanics config file: https://pastebin.com/YidMYS52

## Problem Description
When `old-fishing-knockback:` is true it don't respect WorldGuard `pvp-deny: true`.

### To Reproduce
1. set `old-fishing-knockback: true`
2. enter a region with WG `pvp-deny: true`
3. you can push other players with a fishing rod

### Expected Behaviour
Disable knockback of the fishing rod

### Actual Behaviour
Players can be knocked (out of the region) where pvp is disabled

**Comment by kernitus** [comment]
Do you mean that it does the damage, or that it pulls people when reeling in?

**Comment by martijnpu** [comment]
> Do you mean that it does the damage, or that it pulls people when reeling in?

It pulls people.
When disabling PvP in WG the 'new' fishing rod knockback is disabled, but when using OldCombatMechenics it pushes people. This means players can knock others out of the safezones.

**Comment by ludgart** [comment]
Hello, I have the same problem.
I'm using the "useEntityDamageEvent: true" setting, but with this, player can hit other players in the worldguard protected region.
Disabling the setting "fix" this problem, but create a extra problem for me from other plugins.

Can you please fix the plugin? Maybe moving this line before triggering the damage event:
https://github.com/kernitus/BukkitOldCombatMechanics/blob/84d06627e2c6ccb2aeae56b0c39c0ed4145aed73/src/main/java/kernitus/plugin/OldCombatMechanics/module/ModuleFishingKnockback.java#L97

Regards
ludgart

**Comment by kernitus** [comment]
> Hello, I have the same problem.
> I'm using the "useEntityDamageEvent: true" setting, but with this, player can hit other players in the worldguard protected region.
> Disabling the setting "fix" this problem, but create a extra problem for me from other plugins.
> 
> Can you please fix the plugin? Maybe moving this line before triggering the damage event:
> 
> https://github.com/kernitus/BukkitOldCombatMechanics/blob/84d06627e2c6ccb2aeae56b0c39c0ed4145aed73/src/main/java/kernitus/plugin/OldCombatMechanics/module/ModuleFishingKnockback.java#L97
> 
> Regards
> ludgart

What line are you on about?

**Comment by kernitus** [comment]
Just set `checkCancelled` to true.

**Comment by ludgart** [comment]
This is not really a solution, but I fixed it with coding a separate plugin. Still thank you.
