### ISSUE TITLE
protection damage bug [unsure]

### ISSUE THREAD

**Issue by SladeHazard** [kernitus/BukkitOldCombatMechanics#491]
1.12.2 server ver
ocm ver latest spigot. 1.9.0

Is this a bug
i'm using a sharp 85 diamond axe 
and other player eats golden notch apple while wearing a diamond helmet with protection 10. when i hit him with the sharp 85 axe he dies in 1 hit. now i do the same thing but the player is wearing a diamond helmet with protection 25 this kills him in 2/3 hits???
how to make it so all protection are same after 10 etc.?

my config = https://pastebin.com/RaVk1jqd

**Comment by SladeHazard** [comment]
which options do I need???? to make all protection take same amount of damage

**Comment by kernitus** [comment]
I'm not sure what you're asking here??
