### ISSUE TITLE
Way to use new combat for new players until they toggle it on their own

### ISSUE THREAD

**Issue by bobhenl** [kernitus/BukkitOldCombatMechanics#494]
## Problem
Hi, could you please add way to enable new combat by default and just use old combat if they toggle it by /ocm toggle on their own? The problem is that I wanna use it only as option for players but I wanna prefer new combat.

## Proposed solution
Way in config to enable new combat by default.

**Comment by kernitus** [comment]
You should be able to just disable the `old attack speed` module and then let people use `/ocm toggle`. The toggle command changes the attack speed independent of the module.
