### ISSUE TITLE
No versions work for server version 1.8.8

### ISSUE THREAD

**Issue by HAHALOSAH** [kernitus/BukkitOldCombatMechanics#495]
## Information

* Server Version: 1.8.8

* OldCombatMechanics version: ALL

* Server Log File: java.lang.NoClassDefFoundError: org/bukkit/scoreboard/Team$Option

* OldCombatMechanics config file: 

## Problem Description

No versions work for server version 1.8.8
 
### To Reproduce
1. Get ANY version of OldCombatMechanics
2. Server version 1.8.8
3. Error

### Expected Behaviour
Support for 1.8.8
### Actual Behaviour

java.lang.NoClassDefFoundError: org/bukkit/scoreboard/Team$Option

**Comment by kernitus** [comment]
Yeah obviously, this plugin is to revert 1.9+ mechanics to 1.8, so it does not support 1.8 or below.
