### ISSUE TITLE
Simulate 1.8 critical hits

### ISSUE THREAD

**Issue by SpaceYoshi** [kernitus/BukkitOldCombatMechanics#496]
**Information**

- Server version: Paper 1.16.5
- OCM version: 1.9.0
- OCM config: config with disabled-attack-cooldown and old-tool-damage enabled.
```

disable-attack-cooldown:
  enabled: true
  worlds: []
  generic-attack-speed: 24

old-tool-damage:
  enabled: true
```

**Problem Description**
As @AleMastro stated in #410 , there is a 'problem' with the critical hit behaviour when having the attack speed cooldown disabled. Although I am not an expert on how the critical hits are calculated, I believe this is caused by the critical hit damage multiplier from 1.9+. I would like to see a feature to simulate critical hits like in 1.8. Currently, critical hits deal insane amounts of damage over time compared to critical hits in 1.8.

**Steps To Reproduce**

1. Enable the disable-attack-cooldown module and old-tool-damage module, using the default values.
2. Attack a player frequently in a short amount of time (spam-clicking) using critical hits by jumping and see the resulting damage.

**Expected behaviour**
Critical hit damage simulating 1.8 behaviour.

**Actual behaviour**
Critical hits appear to deal twice as much damage, enabling players to deal insane amounts of damage in a short amount of time.

**Comment by Maroon28** [comment]
If you're running paper, there's an option to disable crits in the paper.yml

**Comment by HumorousFool** [comment]
Additionally if I remember correctly in  1.9 the ability to get crits while sprinting has been removed and sprint is briefly turned off after getting a hit in mid-air.

**Comment by refractored** [comment]
You can a crit damage multiplier using purpur in purpur.yml for now.
"critical-damage-multiplier: 1.5"
