### ISSUE TITLE
TPS Drops

### ISSUE THREAD

**Issue by austv** [kernitus/BukkitOldCombatMechanics#497]
## Information

* Server Version: Tuinity 1.16.5

* OldCombatMechanics version: 1.9.0

* Server Log File: https://timings.aikar.co/?id=8b0fe420aa97484bac333319649adcf6 - https://pastebin.com/raw/trgtEcZY

* OldCombatMechanics config file: https://pastebin.com/raw/uRknR36a

## Problem Description

My server runs normally, 20tps always. However, suddenly, for a few minutes, at random times, performance drops and the report always accuses OldCombatMechanics.
A print from my server TPS: https://prnt.sc/10225q7

 
### To Reproduce
It is irreproducible. The moment is random and sudden. But it only lasts a few minutes.

**Comment by Rayzr522** [comment]
please generate a spark profiler report - https://github.com/lucko/spark

the built-in timings with spigot are a bit hit or miss and aren't as useful as a good old fashioned CPU time breakdown

**Comment by MWHunter** [comment]
I've had 220 players on a OldCombatMechanics 1.16 server and my spark reports indicated no issues with OldCombatMechanics.  Timings is inaccurate and sometimes blames random things if an async task pauses the main thread.
