### ISSUE TITLE
Error being spammed in console while players online

### ISSUE THREAD

**Issue by sopyb** [kernitus/BukkitOldCombatMechanics#498]
Server version: git-Paper-497 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
OCM version: 1.9.0
Error: https://pastebin.com/EpjB2RFe
Config: https://pastebin.com/Cg1VfePz

there are no problems in the functionality itself just the console being spammed if someone is on the server if they are on survival creative adventure or spectator it never stops unless all players leave it's almost impossible to use the console like this so I'd be glad if there's a way to stop it from spamming errors

**Comment by MWHunter** [comment]
This issue is coming from this plugin: https://www.spigotmc.org/resources/tab-1-7-x-1-16-5-free-version.57806/

This is not an OldCombatMechanics error

**Comment by kernitus** [comment]
It seems to be some conflict with the packet injector
