### ISSUE TITLE
EcoEnchants Attack speed

### ISSUE THREAD

**Issue by HyburdzMC** [kernitus/BukkitOldCombatMechanics#503]
Hey,
So I recently installed the plugin [EcoEnchants](https://www.spigotmc.org/resources/%E2%9A%A1-1-15-1-16-5-ecoenchants-%E2%9C%A8-220-custom-enchantments-%E2%9C%85-essentials-cmi-support.79573/) and also its core plugin [Eco](https://www.spigotmc.org/resources/eco.87955/) and soon after I realized that the weapon attack speed override from OCM was gone. So I tried /ocm reload while holding a sword in my hand and the attack speed went back to pre-1.9 update and I tried hitting with it and everything worked fine. But as soon as I scrolled away from my weapon (changed the weapon/tool in my hand) every attack speed on every weapon/tool in my inventory went back to post-1.9 update. 
Any ideas on how to fix this?

**Comment by kernitus** [comment]
That sounds like something EcoEnchants is doing. OCM only sets the attack speed on login/logout or when you use the command.
