### ISSUE TITLE
Splash Potions look like Regular Potions

### ISSUE THREAD

**Issue by Gargant0373** [kernitus/BukkitOldCombatMechanics#505]
## Information

* Server Version: 1.12.2

* OldCombatMechanics version: Build #61

* Server Log File: https://pastebin.com/Ywkcmt1Q

* OldCombatMechanics config file:  https://pastebin.com/Tj5EL6pc

## Problem Description

Splash potions work like splash potions but they look like water bottles when thrown.

 
### To Reproduce
1. Get into creative.
2. Get a splash potion.
3. Throw it

### Expected Behaviour
Show the splash potion being thrown.

### Actual Behaviour

They look like water bottles when thrown.

![image](https://user-images.githubusercontent.com/37416030/111883160-4f2de280-89c2-11eb-8b69-d5f06c748a4f.png)

**Comment by kernitus** [comment]
Fascinating. Did this happen with other versions of the plugin? Could it have anything to do with other installed plugins?
