### ISSUE TITLE
1.8 Sharpness Recalculation

### ISSUE THREAD

**Issue by ziguzagukkun** [kernitus/BukkitOldCombatMechanics#506]
I have been using this plugin for more than 6 months and I think it is a very great plugin.

However, there are two items that I would personally like to see added.

The first is I would like to be able to combine Smite and Sharpness, and Bane of Arthropods and Sharpness, and Smite and Sharpness and Bane of Arthropods in "Survival Mode" using an anvil. Or, in other words, make it possible to combine Mending and Infinite.

Secondly, I'd like to see Sharpness add +1.25 damage, just like it did in 1.8.

**Comment by kernitus** [comment]
The first request is unfortunately out of scope for this plugin. As to the second request, I believe we already recalculate sharpness, did you test the resulting damage to be different?
