### ISSUE TITLE
Projectile knockback less than 1.8

### ISSUE THREAD

**Issue by MWHunter** [kernitus/BukkitOldCombatMechanics#507]
* Server Version: 1.16.5
* OldCombatMechanics version: Dev build 61
* Server Log File: Not important
* OldCombatMechanics config file: Default

### To Reproduce
1. Listen to the knockback packets
2. Throw a snowball, egg, or fishing rod hook at someone
3. The velocity packet sent is (0, 2201, 1747)

### Expected Behaviour
1. Throw a snowball, egg, or fishing rod hook at someone
2. The velocity packet should be (0, 2866, 3200)

### Actual Behaviour

The player takes less knockback than they should

I put the plugin that broadcasts knockback on spigot - https://www.spigotmc.org/resources/knockback-listener.90600/

**Comment by kernitus** [comment]
Is this at all related with #483?

**Comment by MWHunter** [comment]
Somewhat related, as in projectiles do the non-sprinting knockback to the player.

**Comment by kernitus** [comment]
So actually the projectile knockback is given by the ProjectileKnockback module by simply damaging the player a little. Would having the PlayerKnockback module also apply when it's Projectile damage do the trick, or are the calculations specific to when it's two players?

**Comment by MWHunter** [comment]
Yes, letting the player knockback module do this would also work, as long as you don't apply any bonus sprinting knockback.

**Comment by kernitus** [comment]
The packet plugin doesn't seem to be available any more :disappointed:. Would the knockback calculations actually be the same as for living entities (without sprinting knockback of course)?

**Comment by kernitus** [comment]
The relevant code has changed significantly since this issues was opened. A new one can be opened if necessary.
