### ISSUE TITLE
Lava fire damage tick

### ISSUE THREAD

**Issue by Pabsb** [kernitus/BukkitOldCombatMechanics#509]
## Information

* Server Version:  1.16.5

* OldCombatMechanics version: 1.9.0

* Server Log File: N/A

* OldCombatMechanics config file: https://pastebin.com/cfeUB97y

## Problem Description

Fire damage ticks way too fast in lava.

 
### To Reproduce
1. Install OCM
2. Go into Lava
3. See how fast lava fire damage ticks

### Expected Behaviour
Should not tick that fast

### Actual Behaviour

Lava fire damage ticks very fast

**Comment by kernitus** [comment]
If you disable the `old-burn-delay` module does this problem still happen?
