### ISSUE TITLE
World spupport

### ISSUE THREAD

**Issue by Game4ndLive** [kernitus/BukkitOldCombatMechanics#511]
I would love it for you to add world toggle support. Let ut togglew if the OCM is on in one world and off in another.
As my server is 1.16.* Survival, and have a PVP world. I would like to be able to toggle it on in PVP and off in all other worldsl
Is this something you can do?

**Comment by Rayzr522** [comment]
please see the config. you can turn on a world whitelist/blacklist for whichever modules you wish to toggle. there are comments in the config about where and how to do this.
