### ISSUE TITLE
Attack Cooldown broken in one world, but works in a different world

### ISSUE THREAD

**Issue by PixelAgent007** [kernitus/BukkitOldCombatMechanics#513]
## Information

* Server Version: Paper 1.16.5

* OldCombatMechanics version: 1.9.0

* Server Log File: https://pastebin.com/isagnsBw

* OldCombatMechanics config file: https://pastebin.com/JArL5b5S

## Problem Description

I have multiple worlds set up with multiverse, 2 Survival worlds and a KitPVP world. In one of the Survival worlds and in the kitpvp world I disabled the attack cooldown. It used to work in the KitPVP world too, but now it doesnt. It still works in that survival world. I have no idea why. Help is appreciated.

Sorry for bad english

**Comment by kernitus** [comment]
Did you put those worlds' name in the list of worlds under the disable attack cooldown section? I see you only have _world_ in there
