### ISSUE TITLE
I deleted the plugin but it still is on 1.8 combat and not 1.9

### ISSUE THREAD

**Issue by cactus8901** [kernitus/BukkitOldCombatMechanics#514]
I got the plugin and now I want to go back to 1.9 combat so I deleted the plugin, but it is still on 18 combat? How do I fix this? Ive been so stressed about my server. Please help. thanks!

**Comment by kernitus** [comment]
I need to know exactly how you 'uninstalled' the plugin - it isn't the kind of thing you can remove while the server is running

**Comment by cactus8901** [comment]
> I need to know exactly how you 'uninstalled' the plugin - it isn't the kind of thing you can remove while the server is running

The issue is fixed, but thanks anyway
