### ISSUE TITLE
HELP How can i disable critical damage

### ISSUE THREAD

**Issue by Xxyuri2005xX** [kernitus/BukkitOldCombatMechanics#518]
Hello OCM Team,
how can idisable the critical sword attack on OCM plugin on Paper 1.12.2? (i am using viabackwards to allow 1.8)

**Comment by refractored** [comment]
iirc you can disable it in paper.yml

**Comment by Xxyuri2005xX** [comment]
where i can disable them? can you give me the right name of what i need to change?

**Comment by kernitus** [comment]
Duplicate of #410
