### ISSUE TITLE
Knockback on armour stands

### ISSUE THREAD

**Issue by refractored** [kernitus/BukkitOldCombatMechanics#520]
## Information

* Server Version: Purpur-1095

* OldCombatMechanics version: Dev build #62

* OldCombatMechanics config file: https://pastebin.com/1ZpQRyKw

### To Reproduce
1. W tap an armor stand

### Expected Behaviour
The armor stand to stay in place when W tapped
### Actual Behaviour

The armor stand gets knocked back with the W tap. The armor stand does not get knocked back for other regular knockback

https://www.youtube.com/watch?v=ZvWUoGCHcNY

**Comment by kernitus** [comment]
What does "W tap" mean? Are you just hitting an armour stand?

**Comment by kernitus** [comment]
Also I suspect this has to do with the old knockback module, perhaps there should be a black/white list of entities on which to apply knockback.

**Comment by refractored** [comment]
> 
> 
> What does "W tap" mean? Are you just hitting an armour stand?

Basically, W tapping is you stop pressing w after you hit your opponent and start pressing w again when you're about to hit your opponent again. The point of this is to deal extra knockback then just holding w and hitting your opponent.

**Comment by detobel36** [comment]
I think it is not limited to armor stand...

https://www.youtube.com/watch?v=klNiH3YNUTw

**Comment by kernitus** [comment]
Hold on, the old player knockback module only modifiers knockback if the entity being hit is a player. It does not touch anything else at all. Does this problem still happen if that module is disabled?

**Comment by refractored** [comment]
> 
> 
> I think it is not limited to armor stand...
> 
> https://www.youtube.com/watch?v=klNiH3YNUTw

Yeah, it isn't limited to armor stands. I'm saying that W-Tapping/Sprint Resetting shouldn't be knocking back armor stands as well. The module works fine otherwise.

**Comment by refractored** [comment]
Seems like I'm an idiot and armor stands get knocked back without OCM. Sorry for the trouble.
