### ISSUE TITLE
No damage from strength potion

### ISSUE THREAD

**Issue by ludgart** [kernitus/BukkitOldCombatMechanics#523]
## Information

* Server Version: Paper 1.16.5-629

* OldCombatMechanics version: 1.9.0

* Server Log File: /

* OldCombatMechanics config file: https://pastebin.com/XjYfH3h3

### To Reproduce
1. Disable player-crit in the paper.yml config
2. Enable old-tool-damage, disable-sword-sweep, disable-attack-cooldown
3. Drink strength potion
4. Try to hit a player with crit

### Actual Behaviour

No damage to the player

Normally it would work, but because of the issue #410 it's required to disable the crit from paper.

**Comment by kernitus** [comment]
This should be fixed with  9753fe7
