### ISSUE TITLE
OCM toggle voting

### ISSUE THREAD

**Issue by SpecifiedNull** [kernitus/BukkitOldCombatMechanics#525]
## Problem
OCM is either active by default or players have to toggle it manually. this creates disadvantage to those who didn't toggle or don't know about it.

## Proposed solution
It would be a great idea to allow players to vote on which combat system they want the server to be in. once majority of players vote, server will then toggle OCM on or off.
For example players can type "/OCM vote" and then server will broadcast this message in chat:

[Server] Player %player% wants to change combat system to 1.8. You can cast your vote on which mode you prefer and it will be activated instantly based on majority of the votes!
[x] 1.8 combat      [x] 1.16.5 combat

Then players can click on the [x] button in chat to cast their vote, then it calculates the total votes and automatically toggle the combat system and broadcast the result of the poll.
There should then be a cooldown how often players can do /ocm vote from the last time vote was done.

**Comment by refractored** [comment]
Im pretty sure you can do this with other plugins.

**Comment by kernitus** [comment]
Both this and  #179 require quite a lot of work to make happen, but this as a feature seems useless compared to  #179.
