### ISSUE TITLE
old-player-knockback is incompatible with other plugins

### ISSUE THREAD

**Issue by ghost** [kernitus/BukkitOldCombatMechanics#527]
## Information

* Server Version: 1.16.5 Purpur

* OldCombatMechanics version: 1.9.0 (dev build)

* Server Log File: irrelevant

* OldCombatMechanics config file: irrelevant

## Problem Description

The problem is that in my server a plugin under some situations removes knockback from players by cancelling the entity knockback event, however OldCombatMechanics ignores this for melee battles and still keeps knockbacking the player. is this fixable?

### Expected Behaviour
expected the player to not get knockbacked at all
### Actual Behaviour

the player got knockbacked as usual after melee hit

**Comment by kernitus** [comment]
Sound similar to #520. What plugins exactly does it interfere with?

**Comment by GovindasOM** [comment]
custom

**Comment by kernitus** [comment]
We now ignore the VelocityChangeEvent if it was cancelled, can you please check if the module still interferes?
There might still be issues with the listener priorities, do your custom plugins use `NORMAL` priority?

**Comment by GovindasOM** [comment]
the priority was high, I now tested with normal priority and the issue persists, I have also updated oldcombatmechanics to a dev build from yesterday

**Comment by kernitus** [comment]
Should be fixed with caf99eb
