### ISSUE TITLE
Random knockback when hitting the ground

### ISSUE THREAD

**Issue by scraft-official** [kernitus/BukkitOldCombatMechanics#528]
## Information

* Server Version: 
git-Paper-1618 (MC: 1.12.2)

* OldCombatMechanics version: 
1.9.0 (#63 TEST BUILDS)

* OldCombatMechanics config file: 
https://pastebin.com/xBkUWP0C

## Problem Description

Sometimes (1/30) on the latest version with knockback module enabled in ocm, i got pushed in random direction when hit the gorund. It look like that maybe one of the listeners, take the ground hit as a damage from another player (maybe the victim it self). This issue happen rarely, but it can relly break the gameplay, because i'm making a BedWars server and when it happens on bridges, players just get pushed out of them.

 
### To Reproduce
1. Climb 8 blocks above the ground and jump.
2. Repeat it 20-30 times.
OR
1. Make stairs (5 block above the gorund), and try jumping 10 times with sprint enabled.

### Actual Behaviour

It's pushing the player sometimes in a different direction when hit the gorund.

**Comment by kernitus** [comment]
@scraft-official Can you please try with a newer test build to see if this is still a problem?

**Comment by MeowMC** [comment]
I can confirm this still happens in the latest release
