### ISSUE TITLE
shield-damage-reduction not working as intended

### ISSUE THREAD

**Issue by M4RC0Sx** [kernitus/BukkitOldCombatMechanics#529]
## Information

* Server Version: git-Tuinity-"3eda860" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT

* OldCombatMechanics version:  OldCombatMechanics by kernitus and Rayzr522 version 1.9.0 (latest from Jenkins)

* OldCombatMechanics config file: https://pastebin.com/41qfKBLc

## Problem Description

shield-damage-reduction option is not working as intended. When disabling it, you become completely invulnerable. But when you enable it, the percentage is not working. For example, having this enabled, if I get hit with a sword and I don't block it, I get 2 hearts damage but if I block it with the shield, I get 3 hearts damage.

 
### To Reproduce
1. Enable shield-damage-reduction
2. Hit with a sword and don't block the hit
3. Hit with a sword and block the hit
4. See how the damage is not consistent, you should recieve more damage if you are not blocking.

### Expected Behaviour
You should recieve more damage if you are not blocking.

### Actual Behaviour

You get more damage blocking with a shield.

**Comment by kernitus** [comment]
Should be fixed in dcd9ed1

**Comment by M4RC0Sx** [comment]
@kernitus It is working with players but not with mobs.

**Comment by kernitus** [comment]
@M4RC0Sx mobs as in mobs attacking you while holding your shield up? Do you have any debug log data of that example?
