### ISSUE TITLE
1.17 packets error

### ISSUE THREAD

**Issue by x9nico** [kernitus/BukkitOldCombatMechanics#534]
## Information

* Server Version: Spigot 1.17

* OldCombatMechanics version: 1.9.0

* Server Log File: 

https://pastebin.com/yueGjypC
https://pastebin.com/JEBjWHuL

* OldCombatMechanics config file: 

https://pastebin.com/sGse7Z9j

## Problem Description

When I'm loading the plugin, I have these errors in logs, maybe incompatible with Java 16 and 1.17?

 
### To Reproduce
1. Upload the plugin on your server
2. Restart your server
3. And then, you have errors when the plugin load

### Actual Behaviour

It does the errors in logs (see the pastebin link)

**Comment by kernitus** [comment]
@rayzr522 @I-Al-Istannen reflection machine broke?

**Comment by thiagogebrim13** [comment]
In 1.17 all plugin configuration is invalid and does not work

**Comment by x9nico** [comment]
> In 1.17 all plugin configuration is invalid and does not work

Yes, in Java 16 there is some breaks in reflections

**Comment by kernitus** [comment]
It looks like the NMS packet names changed in 1.17, so this needs to be accounted for. In the meantime you could disable the sweep animation feature and the no collisions feature if you want to avoid those errors.

**Comment by thiagogebrim13** [comment]
It has forecast?

**Comment by thiagogebrim13** [comment]
> It looks like the NMS packet names changed in 1.17, so this needs to be accounted for. In the meantime you could disable the sweep animation feature and the no collisions feature if you want to avoid those errors.

It has forecast?

**Comment by x9nico** [comment]
> It looks like the NMS packet names changed in 1.17, so this needs to be accounted for. In the meantime you could disable the sweep animation feature and the no collisions feature if you want to avoid those errors.

I have always the error.

**Comment by rayzr522** [comment]
@x9nico please try this build -- there will still be missing functionality until we fix our 1.17 support, but the plugin should at least be able to load now and basic functionality (like attack cooldown) will still work: https://ci.rayzr.dev/job/OldCombatMechanics/74/

**Comment by x9nico** [comment]
> @x9nico please try this build -- there will still be missing functionality until we fix our 1.17 support, but the plugin should at least be able to load now and basic functionality (like attack cooldown) will still work: https://ci.rayzr.dev/job/OldCombatMechanics/74/

I tried this build.
There is the errors: https://pastebin.com/mMSkkhDq

**Comment by rayzr522** [comment]
@x9nico yes, these are to be expected as there's still parts of the plugin which don't support 1.17. however, does the plugin now load for you and function for the most part?

**Comment by x9nico** [comment]
> @x9nico yes, these are to be expected as there's still parts of the plugin which don't support 1.17. however, does the plugin now load for you and function for the most part?

No, I have the plugin in red again.

**Comment by thiagogebrim13** [comment]
It worked for me, but the errors keep appearing on the console

**Comment by thiagogebrim13** [comment]
1.17 BUGS:
The player dies and gets buggy, he doesn't take damage if he's in full armor, the mace isn't changing to 1.8

**Comment by x9nico** [comment]
Hey, any news about the fixes ?

**Comment by kernitus** [comment]
We're working on it in PR #536

**Comment by USBCharger** [comment]
> @x9nico yes, these are to be expected as there's still parts of the plugin which don't support 1.17. however, does the plugin now load for you and function for the most part?

Using the latest build on purpur 1.17, I can't get it to load

**Comment by x9nico** [comment]
Hey, the bugs that you fixed before affect the 1.17.1.

**Comment by kernitus** [comment]
Fixed with cefbd0d
