### ISSUE TITLE
Might not be a bug

### ISSUE THREAD

**Issue by Segid0705** [kernitus/BukkitOldCombatMechanics#535]
## Information
 
* Server Version: 1.16.5 Paper Java 16

 

* OldCombatMechanics version: 1.9.0

* Server Log File: none

* OldCombatMechanics config file: https://pastebin.com/qxnw2CUK

## Problem Description

Alright so i ve been needing to use 1.16.5 but wanted old pvp for events. I installed this plugin and disabled sword shield, removed 1.16 noises made attack speed like 50 and some other stuff, but I cant exactly seem to replicated 1.8. pvp. Im sorry im new to github so if this isnt the right place for this my bad, but could i get the exact config to replicate 1.8? it just feels a bit off yknow, I attached my config file
 
### To Reproduce
Steps to reproduce the behavior: none
1.
2.
3.

**Comment by refractored** [comment]
Try with the builds on Jenkins.

**Comment by Segid0705** [comment]
ig it works now, thanks a lot it feels better smhow
