### ISSUE TITLE
Golden apple/enchanted

### ISSUE THREAD

**Issue by CaptainLaStar** [kernitus/BukkitOldCombatMechanics#538]
Hello,
I have a suggestion for plugin OldCombatMechanics.

I would like you to add a option of the config of apple and cooldown for the pvp improve !
The player must not eat an enchanted golden apple if he has already eaten a golden apple and vice versa.
This will not take too many apples and therefore make the pvp even better.

In a few lines of config, as an example, this could give:

If the player is to eat a "Golden apple", then he must wait until the end of the cooldown of that Golden apple to be able to eat a Golden apple enchanted.
enabledoption : true or false

If the player is to eat a Golden apple enchanted, then must wait until the end of the cooldown of that Golden apple enchanted to be able to eat a Golden apple, so he cannot eat both at the same time.
enabledoption: true or false

Cordially;

**Comment by kernitus** [comment]
We already have this feature.
