### ISSUE TITLE
Toggle cooldown via console for other players

### ISSUE THREAD

**Issue by MaxOette** [kernitus/BukkitOldCombatMechanics#539]
Hello, i really like your great Plugin!

I have a question: I dont want the players to be able to toggle 1.8 cooldown for themselves.
So players shouldnt get the oldcombatmechanics.toggle permission.
I want toggle their cooldown via console during specific events, but i couldnt find a command to do so.

(for example: /ocm toggle MaxOette)

It would be even better, if there were specific commands for on/off, like:
/ocm on MaxOette 
and
/ocm off MaxOette
since i cant be sure which player has ocm currently enabled or not while being in console.

Maybe i just overlooked something, but
otherwise i would apprechiate it if a command like this could be implemented.

Thank you!

**Comment by refractored** [comment]
iirc i dont think you can toggle OCM per player in the first time. #179

**Comment by MaxOette** [comment]
is it possible to toggle it for each world individually per command?

**Comment by subancy** [comment]
@kernitus this feature would be very much appreciated. Thank you (:

**Comment by refractored** [comment]
https://github.com/kernitus/BukkitOldCombatMechanics/issues/179#issuecomment-443530585
