### ISSUE TITLE
Old tool damage spamming console

### ISSUE THREAD

**Issue by NeviskDOBLOCO** [kernitus/BukkitOldCombatMechanics#541]
## Information

* Server Version: Purpur 1.17.1

* OldCombatMechanics version: 1.10.0BETA

* Server Log File: https://pastebin.com/QfV688ka

* OldCombatMechanics config file: https://pastebin.com/ZiCkupH6

## Problem Description

Oldtooldamage generating errors when hitting players
 
### To Reproduce
1. Set oldtooldamage to true
2. Hit a player

### Actual Behaviour

Send this error to the console for all hits: https://pastebin.com/QfV688ka

**Comment by kernitus** [comment]
Duplicate of #537
