### ISSUE TITLE
InventoryClickEvent array out of bounds

### ISSUE THREAD

**Issue by ghost** [kernitus/BukkitOldCombatMechanics#542]
* Server Version: This server is running Purpur version git-Purpur-1171 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT) 

* OldCombatMechanics version:  Version of OldCombatMechanics, 1.9.0 

* Server Log File:  https://pastebin.com/bQWK453y

**Comment by rayzr522** [comment]
do you have any clue what action people are taking that is causing this? it must be some kind of GUI or inventory that they're interacting with
