### ISSUE TITLE
When a player attacks us, the sprint is canceled 

### ISSUE THREAD

**Issue by NoaXelo** [kernitus/BukkitOldCombatMechanics#543]
Hello,
Since the last version of OCM , when a player takes a hit , his sprint is canceled.
It is very annoying because we have a custom KB is close to that of 1.8 (the server is in 1.12) , It's very difficult to get out of a combo without a sprint.. I'm sure it comes from OCM, because if I downgrade the version, the problem is no longer there , Despite that I keep the new version which is much better.

The different information :
Paper Spigot 1.12.2
With Bungeecord (Waterfall 1.17.1, same problem 1.16.x version)
OCM version 1.9.0
ip (to test the pvp) : play.battle-adventure.eu

Thanks for your help !
Noa.

**Comment by kernitus** [comment]
Can you please follow the issue template and attach your config file.
