### ISSUE TITLE
Spam in console lastest 1.17 build (spigot build)

### ISSUE THREAD

**Issue by jassyel** [kernitus/BukkitOldCombatMechanics#549]
## Information

* Server Version:  1.17.1

* OldCombatMechanics version: 

https://pastebin.com/Fr9KjDKg

* Server Log File: 

* OldCombatMechanics config file: 

### To Reproduce
1. Download lastest spigot build 1.17
2. Install in server
3. Check console

**Comment by I-Al-Istannen** [comment]
Can't reproduce.

You are also most certainly *not* using "the lastest spigot buil 1.17", as your log says the code is from a `patched_1.17.1.jar:git-Airplane-57` jar.

What server software do you use? Does it work with the latest *spigot* release?
