### ISSUE TITLE
Spartan Regen Check error

### ISSUE THREAD

**Issue by GreenArrowlol** [kernitus/BukkitOldCombatMechanics#551]
Mc version - 1.16.5
oldcombatmechanics version - v1.10.0

Just updated the plugin to v1.10.0 and latest when I went to see the console for something else I saw this spam in the console from a while.
https://pastebin.com/AK3j7Dhn

Do tell me if I have to downgrade the version back or have to do anything else.

**Comment by kernitus** [comment]
This seems to do with the Spartan anticheat check - are you using that plugin? Can you post your config.yml please?
