### ISSUE TITLE
OCM disables the chat of my chat plugin

### ISSUE THREAD

**Issue by MinecollYT** [kernitus/BukkitOldCombatMechanics#556]
## Information

* Server Version: Paper 1.16.5

* OldCombatMechanics version: 1.10.0

* Server Log File: `[OldCombatMechanics] [DEBUG] PacketInjector: Received a packet THAT IS NO PACKET: class org.mcnative.runtime.api.protocol.packet.type.MinecraftChatPacket org.mcnative.runtime.api.protocol.packet.type.MinecraftChatPacket@401116a8`

* OldCombatMechanics config file: https://pastebin.com/Z3cGRRWA

## Problem Description

Chat does not work / message don't appear in the chat after they have been send

 
### To Reproduce
1. Use DKPerms and OCM
2. Write smth in chat

### Expected Behaviour
the message gets send

### Actual Behaviour

message not visible

**Comment by kernitus** [comment]
Hello, you mention it's _your_ plugin OCM is conflicting with, might I ask why it's sending chat packets that do not inherit from `Packet` in first place?

**Comment by I-Al-Istannen** [comment]
Can you try the artifact of the PR @MinecollYT ? I reuploaded it [here](https://github.com/kernitus/BukkitOldCombatMechanics/files/7090073/OldCombatMechanics.zip)

**Comment by MinecollYT** [comment]
I can test it in the next few days

**Comment by MinecollYT** [comment]
Seems like it got fixed, thank you <3
