### ISSUE TITLE
Full Armour Bug

### ISSUE THREAD

**Issue by PirataGu** [kernitus/BukkitOldCombatMechanics#557]
## Information
* Server Version: PAPER 1.16.4

* OldCombatMechanics version: 1.10.0

* Server Log File: https://pastebin.com/92dE2FUw

* OldCombatMechanics config file: https://pastebin.com/SfQc6kLK

### To Reproduce
1. 1 versus 1 with a player with full diamond armour with protection 4 and unb 3 (or netherite armour with the same enchantments)
2. hit on the player and causes 0 health points
3. just causes lost health points when you take off a piece of the armour
4. we used sharpness 5 on the swords (diamond and netherite)

**Comment by kernitus** [comment]
I'm gonna be needing an actual debug log with the damage being done and received on both sides to even have a clue what the problem might be. Please enable debug mode in the config.
