### ISSUE TITLE
1.10.0 is bugged

### ISSUE THREAD

**Issue by AlarUnderscoreX** [kernitus/BukkitOldCombatMechanics#561]
## Information

* Server Version: 1.17.1

* OldCombatMechanics version: 1.10.0

* Server Log File: https://pastebin.com/YP7D14KS

* OldCombatMechanics config file: https://pastebin.com/FBB1M3tb

## Problem Description

the 1.8 hit delay turns off when you scroll off an item to another even if it's the same item like stone to stone
 
### To Reproduce
1. turn off the server
2. reset the config

**Comment by kerostampcrab** [comment]
I think they might mean the hit delay bar thing shows up for 0.1 second when scrolling through items, because I have this problem too. It's really just super minor but it's there.

**Comment by kernitus** [comment]
But that's just how the client renders a very fast weapon. As far as I know there's nothing that can be done about that.
