### ISSUE TITLE
1.8 colldown

### ISSUE THREAD

**Issue by TeruHUB** [kernitus/BukkitOldCombatMechanics#564]
hi, i have a [1.16.5] server and if i enter in 1.8 i have an loading animation.
![2021-10-24_21 03 38](https://user-images.githubusercontent.com/80040321/138746121-799df21b-b723-40a8-8d3f-2144a5f549ab.png)
this image are in made in 1.16.5 server but im play with 1.8 (lunar client) don't happen in other server

**Comment by kernitus** [comment]
What seems to be the problem here? And why are you using a 1.8 client anyway?
