### ISSUE TITLE
'Error in a packet listener (send)'

### ISSUE THREAD

**Issue by kerostampcrab** [kernitus/BukkitOldCombatMechanics#566]
## Information

* Server Version: Purpur version git-Purpur-1385 (MC: 1.17.1)

* OldCombatMechanics version: 1.10.0, dev #  58

* Server Log File: Trust me. You do not want this, it's way too big because of the errors OCM rapidly sends. This is the best i can give: https://paste.sparked.host/irolopezug.properties

* OldCombatMechanics config file: https://paste.sparked.host/zojijukuru.yaml

## Problem Description

It will throw out this error rapidly when a player is online and enters a world where OCM is enabled.
 
### To Reproduce
1. Configure OCM for your worlds.
2. Go into a world you specified to OCM you want to use whatever 1.8 PvP mechanics you wanted.
3. See the beautiful errors, clogging up your log files and making them in a day 106 MB big.

### Expected Behaviour
Well, of course i don't want these errors. Soon my used disk space will go from 12 GBs to 50 GBs because of the logs!
### Actual Behaviour

https://paste.sparked.host/irolopezug.properties OCM will throw this error rapidly.

**Comment by kernitus** [comment]
Does this also happen if you have the exact same setup but run the server using Spigot? I suspect Purpur might be doing some wacky optimisation with the packets

**Comment by kerostampcrab** [comment]
Sry, ment to try this 4 days ago but my brain shifted from that to doing something else, so did yesterday.

**Comment by kerostampcrab** [comment]
I might just not test it as I somehow keep forgetting to do this...
