### ISSUE TITLE
Weird hits

### ISSUE THREAD

**Issue by DotDotas** [kernitus/BukkitOldCombatMechanics#567]
.

**Comment by kernitus** [comment]
You increased the attack-frequency, which means the invulnerability overdamage can kick in

**Comment by DotDotas** [comment]
In the first video attack-frequency playerDelay is set to 18 (default), but something is still wrong there's to many hits

**Comment by VytskaLT** [comment]
Same issue, in 1.9.0 it works fine.
Here's a video (look at the health):
https://user-images.githubusercontent.com/35194709/141801517-26ce5317-7a64-4404-85b1-da747d3e2c18.mp4
