### ISSUE TITLE
Sprinting

### ISSUE THREAD

**Issue by DotDotas** [kernitus/BukkitOldCombatMechanics#568]
.

**Comment by kernitus** [comment]
wat

**Comment by DotDotas** [comment]
Sprint gets removed after u get hit by another player

**Comment by FieryMewtwo** [comment]
They're saying if you get hit while sprinting, you stop sprinting, even if you shouldn't. For them, holding down Ctrl is the sprint key. So they're holding Sprint as usual, but when they get hit by another player, even while holding Ctrl, they suddenly stop sprinting.
