### ISSUE TITLE
Fall damage gives knockback

### ISSUE THREAD

**Issue by crazymarty** [kernitus/BukkitOldCombatMechanics#569]
## Information

* Server Version: 1.17.1

* OldCombatMechanics version: 1.10.0

* Server Log File: 

* OldCombatMechanics config file: https://paste.gg/p/anonymous/36e8630e9d95429a9dceb1b114527689

## Problem Description

Players sometimes get knockback when they get fall damge

 
### To Reproduce
Just put the plugin in your server and try to get fall damage again and again, you will eventually get knockback for fall damage

**Comment by nicku1** [comment]
Have the same problem, one of our moderators provided me with video. I hope it can help with investigating the issue (3:30): https://youtu.be/kO6QsbbF9W4?t=211
I use Tuinity 1.15.2 and OCM 1.10.0

**Comment by hswhsw610** [comment]
this happens to my network very often too which is sooo annoying..

**Comment by MWHunter** [comment]
Clear the hashmap of knockback on the start of each tick to fix it!

**Comment by hswhsw610** [comment]
> 

you can pull req

**Comment by crazymarty** [comment]
Hey, this issue is still not fixed.

Server Version: Paper - 1.18.1
Plugin Version: 1.10.0

**Comment by kernitus** [comment]
Fixed with caf99eb59e894ba6a143cbcbcf671203128476cb
