### ISSUE TITLE
Question: Support settings

### ISSUE THREAD

**Issue by Alcrafter-YT** [kernitus/BukkitOldCombatMechanics#570]
I am using OldCombatMechanics together with Spartan AntiCheat, and I was wondering what the setting "spartan-cancel-ticks: 1" in the config.yml corresponds to and if I will ever have to change/modify it. Would be nice if you could explain. Have a great day :-)

**Comment by kernitus** [comment]
It's just a compatibility setting because spartan would kick when OCM changes some of the damage and knockback related values
