### ISSUE TITLE
Brewing stand not working

### ISSUE THREAD

**Issue by AstragoDE** [kernitus/BukkitOldCombatMechanics#571]
## Information

* Server Version: PaperMC 1.17.1-378

* OldCombatMechanics version: 1.10.0

* Server Log File: https://gist.github.com/AstragoDE/cad01d8f26d6c9bc871e559d50c06ffe#file-latest-log

* OldCombatMechanics config file: https://gist.github.com/AstragoDE/cad01d8f26d6c9bc871e559d50c06ffe#file-config-yml

## Problem Description

The brewing stand does not work. The progress bar of the brewing stand jumps back to 0% after hitting 100%. No Items get consumed, and the water bottles do not change to an awkward potion.

 
### To Reproduce
1. Place brewing stand
2. Fill brewing stand with blaze powder, water bottles and nether warts
3. Wait until the progress bar fills up

### Expected Behavior
The water bottles should change to an awkward potion. 

### Actual Behavior

The water bottles do not change, and no items get consumed.

**Comment by kernitus** [comment]
If you disable the `old-brewing-stand` module does this still happen?

**Comment by AstragoDE** [comment]
It doesn't work, even if the module is disabled-

**Comment by kernitus** [comment]
Any chance you have another plugin that could be conflicting? Because if the module is disabled OCM should not be touching brewing stands at all.

**Comment by LoXR** [comment]
Tried this aswell, and still the same. Removed the plugin, and its OCM affecting brewing stands, re-add OCM and the brewing stands progress keeps resetting.

**Comment by toonystank** [comment]
I removed the brewing stand from `interactive:` and disabled `old-brewing-stand:`. It works now
