### ISSUE TITLE
hit bug

### ISSUE THREAD

**Issue by Chiquis2005** [kernitus/BukkitOldCombatMechanics#573]
## Information

* Server Version:  1.16.5

* OldCombatMechanics version: 1.10.0

* Server Log File: [LINK](https://pastebin.com/ga3HjQEi)

* OldCombatMechanics config file: [LINK](https://pastebin.com/fhrs3bz8)

## Problem Description

I changed the version of OldCombatMechanic and started this bug, when you hit a person it's like a combo of hits.

 
### To Reproduce
1.  change plugin version

https://user-images.githubusercontent.com/44950448/142248423-672d6851-0bbe-417c-8194-3a65b9a705a4.mp4

**Comment by kernitus** [comment]
What exactly are you trying to show here? What do you expect to happen??
