### ISSUE TITLE
Client side mod for old animations

### ISSUE THREAD

**Issue by jmart384** [kernitus/BukkitOldCombatMechanics#585]
So I have a 1.16.5 Paper server running with Screaming Bed Wars, ocm and viaBackwards/rewind. I really like how smooth 1.8 animations are but the shield solution for newer versions feels more clunky so I was wondering if it was possible to have old combat mechanics with your plugin and old combat animations with a client side mod, I tested one called Golden age combat linked here:

https://www.curseforge.com/minecraft/mc-mods/golden-age-combat? 

It seems like it almost works, here's a video of what it does: https://youtu.be/D71Jja__QqQ 

So could you possibly add some form of compatibility with this mod or even one like it or possibly even make your own client side mod for this plugin so that users on 1.16 can have old combat mechanics and old combat animations. I'm pushing for 1.16 so hard because I also want to try and use a voice chat plugin but the client side mods for it are only availible for 1.16 or higher. If there's already a mod that allows this could you tell me what it is?

**Comment by kernitus** [comment]
This is out of scope for this plugin - OCM is just a Bukkit plugin and making a mod is not the objective. However, if somebody else made such mod, we could easily make it compatible with it.
