### ISSUE TITLE
Old armour durability can't eat gapples while damaged

### ISSUE THREAD

**Issue by Pulsih** [kernitus/BukkitOldCombatMechanics#586]
## Information

* Server Version: 1.13.2

* OldCombatMechanics version: 1.10.0

* Server Log File: https://pastebin.com/bbmhFRdN

* OldCombatMechanics config file: https://pastebin.com/wvaWr811

## Problem Description

If enabling the old-armor-durability feature, players can't eat gapples or stuff while being damaged, i think because the plugin update the player inventory while eating, and resetting the animation.

 
### To Reproduce
1. Just enable the old-armor-strenght feature and get hitted while eating

### Expected Behaviour
You should be able to eat gapples normally

### Actual Behaviour

You won't be able to eat gapples, and you will die ( My server is a FFACombo )

**Comment by kernitus** [comment]
You mention both the old armour strength and old armour durability modules, which one is it that you think causes the issue?

**Comment by kernitus** [comment]
Duplicate of #405
