### ISSUE TITLE
Sprint

### ISSUE THREAD

**Issue by VanishCZE** [kernitus/BukkitOldCombatMechanics#593]
Hello, during pvp disables sprint after "combo" even during togglesprint, it's like that in new versions so I would like to ask if there is any way to remove it.

https://pastebin.com/MwtTHppn

**Comment by VanishCZE** [comment]
I couldn't find it in the plugin.

**Comment by MWHunter** [comment]
This is a vanilla mechanic that's existed even in versions as old as 1.7.  You need to reset your sprint in order to deal more knockback.  It's always been like that.

**Comment by kernitus** [comment]
I would say this is out of scope for this plugin due to it focusing on change made with 1.9+
