### ISSUE TITLE
I see no information on 1.18.1 release

### ISSUE THREAD

**Issue by Schards** [kernitus/BukkitOldCombatMechanics#596]
I feel like I have looked all around the pages, issues and comments of this plugin  and I cannot see any information about if this works on 1.18 or when if it's being worked on / an estimated eta for its release. Can someone please let me know?

**Comment by rayzr522** [comment]
as far as I know there's nothing stopping it from working on 1.18.1. you're more than welcome to test it yourself and report any bugs you find!
