### ISSUE TITLE
disable per world

### ISSUE THREAD

**Issue by GAMERFORCE99** [kernitus/BukkitOldCombatMechanics#600]
i dont the think the black list works how do i disable the all of the plugins and its features in some world? cuz 
worlds-is-blacklist: true
  worlds: [ ]
  doesnt work even when i put all the worlds in the [ ] 
  if i am doing it right can you tell me how the enable and disabling features works?

**Comment by detobel36** [comment]
If I'm not wrong you need to add the list like this:
````YAML
worlds:
- world
- spawn
````

Have you try that ?

**Comment by GAMERFORCE99** [comment]
wait it still doesnt work i did with space like this
worlds-is-blacklist: true
  worlds:
  - world
  - world_nether
  - builder
  - world_the_end
  is it wrong like this?

**Comment by GAMERFORCE99** [comment]
> Normally both will works...
> 
> Did you restart your server after update the configuration ? Are you sure you don't have made a mistake in the name of the worlds ?

i did oldcombatmechanics reload and no i dont have misstakes with the worlds names do
idk why its like this
