### ISSUE TITLE
Disabled plug-in for specific item or players or zone

### ISSUE THREAD

**Issue by GabrielChev** [kernitus/BukkitOldCombatMechanics#610]
Hello,

Is their a way to disabled the plug-in just for specific item or zone ?
I use the plug-in but i want continue to use the new version at the same time in the same server.
For exemple can i rename a sword and re-apply the 1.18 stats for this specific item renamed ?
Other way : Is it possible in a specific zone to disable all the plug-in on the same server and same world?

Thanks a lot in advance

**Comment by kernitus** [comment]
The plugin works on a worlds or player level, not on an item level. You can specify which worlds the whole plugin or the various modules are enabled in by changing the `worlds` list in the config. You can also use the `toggle` and `enable/disable` commands to change the attack version for players programmatically. More information about the commands can be found [here](https://github.com/kernitus/BukkitOldCombatMechanics/wiki/Commands).

**Comment by GabrielChev** [comment]
The plugin does't works correctly on a world level. I blacklisted a world but the calcul of armor resistance (or domage taken i don't know) continue to be modify on it. Can you help me on that, i have disabled ALL in config file for this world and add it in blacklist

**Comment by detobel36** [comment]
So, you request a new feature, because an existing feature has a bug ?   
May be we can try to fix the bug before to add new feature 😉 

I think we can begin to try to debug if you give us your configuration file, the version of the plugin and the version of the server.
Please check also you don't have error in logs.

**Comment by kernitus** [comment]
Following the bug at #615
