### ISSUE TITLE
Disabling OldCombatMechanics

### ISSUE THREAD

**Issue by aAlfonsito** [kernitus/BukkitOldCombatMechanics#613]
I have a problem ;c

https://pastebin.com/0kQYTwd7

my problem is 

https://pastebin.com/uCC9eW0Z

**Comment by kernitus** [comment]
What version of Bukkit/Spigot are you running?

**Comment by aAlfonsito** [comment]
Both are in their latest version

**Comment by aAlfonsito** [comment]
an answer please

**Comment by SrBedrock** [comment]
> Both are in their latest version

That doesn't answer the question

Plugin version: v1.11.0
Server Version: ???

**Comment by aAlfonsito** [comment]
Server version 1.8

**Comment by detobel36** [comment]
I don't understand, why do you use OldCombatMechanics, a plugin that reproduce 1.8 PvP on "new versions" of minecraft, is you are on 1.8... You want to reproduce a PvP that's already in place on your server.

And for your information, 1.8 is not the "latest" version of minecraft 😝
