### ISSUE TITLE
Plug-in affects disabled worlds

### ISSUE THREAD

**Issue by GabrielChev** [kernitus/BukkitOldCombatMechanics#615]
Hello,

Is there a way to completely disable the plug-in in a world ?

I put the world "world" in world blacklist and after in all blacklists for turn-off the plug-in just in this world.
But i noted that :

The shield continues to not deflects the arrow like normally in vanilla 1.18
The calculation of damage is not the same as in vanilla (Full Protection 4 netherite is much too resistant, don't know if it's because of the damage given calculation or protection enchant claculation or maybe netherite)

My server is Paper-Spigot version 1.18.2

Here is my config.yml (in txt format for transfer) :

[config.txt](https://github.com/kernitus/BukkitOldCombatMechanics/files/8956068/config.txt)

No log error

Thanks in advance for your help

**Comment by kernitus** [comment]
Would you have some examples of what the damage being actually done vs what you expect it to be? Perhaps you could collect logs by turning on debug mode in the config

**Comment by GabrielChev** [comment]
It would take a long time to set up BUT If You have any doubts about the damage, Note that my configuration affects a blacklisted-world also in another way :

- shield-damage-reduction is active in the blacklisted world
- shield do not block arrow in a blacklisted world

Their is a way to COMPLETLY disable the plug-in in a specific world ? (check my config.txt)

**Comment by rayzr522** [comment]
@GabrielChev in the future, before reporting an issue please ensure that your config format is valid via a YAML checker tool such as https://yamlchecker.com/. your indentation is messed up, you have only a single space in a lot of places where you actually need two spaces -- make sure the indentation aligns with the other settings around it :)

I tested on the latest stable release (1.10.0) with `worlds-is-blacklist` set to both `true` & `false` and in both cases the module behaved as expected. for example with blacklist mode set to false, the following resulted in shield damage reduction only being enabled in `world`:
```yaml
shield-damage-reduction:
  # This module allows changing the damage reduction behaviour of shields
  enabled: true
  worlds: [world]
```
and then with blacklist mode set to `true`, it resulted in the module being enabled in every world except `world`, as expected

if you check your console I imagine you will see a huge number of errors from your malformed YAML file. i suggest using a tool like [VSCode](https://code.visualstudio.com) for editing YAML files as it provides proper syntax highlighting, smart indentation, etc :3

**Comment by rayzr522** [comment]
apologies for the previous (since deleted) reply, I had several tabs open and replied to the wrong issue oops

the issue is that you have `worlds: [world]` at the root level of the config, not under the `shield-damage-reduction` section. if you wish to blacklist it only in `world`, you would need to do the following:
```yaml
shield-damage-reduction:
  # This module allows changing the damage reduction behaviour of shields
  enabled: true
  worlds: [world]
```
as of right now there is no way to whitelist/blacklist ALL modules simultaneously, so you'll need to specify this `worlds` section under each module section. i will look into adding a global toggle in the future & also updating the default config file as it is missing the `worlds` section for that module!
