### ISSUE TITLE
Ability to effectively turn whole plugin off for certain players

### ISSUE THREAD

**Issue by Shodwriter** [kernitus/BukkitOldCombatMechanics#616]
The command `/ocm toggle [player] on/off` already exists, but that only affects the combat cooldown. I think it would be useful to have toggles for all features, such as tool damage, crafting, old golden apples, etc. This would be useful if you were using a plugin such as GeyserMC and you wanted bedrock players to have no combat cooldown but have different tool damages to make combat more interesting. An example syntax could be `/ocm toggle [player] all on/off` or `/ocm toggle [player] old-player-regen on/off`. I don't know if this is possible but it would be useful to have.

**Comment by kernitus** [comment]
Duplicate of #179
