### ISSUE TITLE
Enable Bow Boosting on 1.18

### ISSUE THREAD

**Issue by GregKW** [kernitus/BukkitOldCombatMechanics#625]
Hello, I was wondering how I could enable bow boosting on 1.18.2?

**Comment by kernitus** [comment]
There's a module to _disable_ bow boosting, but not one to enable it. Unless you mean you just want to disable the disable bow boosting module.

**Comment by GregKW** [comment]
Is there a way to **enable** it in 1.18?

**Comment by kernitus** [comment]
No, there is currently no way of doing that. I don't think it's within the scope of this plugin either because it was not a change introduced around 1.9 that significantly affected combat.
