### ISSUE TITLE
Jenkins site appears offline

### ISSUE THREAD

**Issue by zS0bye** [kernitus/BukkitOldCombatMechanics#634]
The site https://ci.rayzr.dev/job/OldCombatMechanics/ is down, I can't download the latest build. I need compatibility for 1.19.3 if it exists

**Comment by kernitus** [comment]
That's strange, @rayzr522 is the build server down? In the meantime, you may download builds by clicking on the green tick next to a commit, details, and then download the artefact.

**Comment by kernitus** [comment]
It is back up now and has been updated.
