### ISSUE TITLE
Delay between attacks is much less than 1.8

### ISSUE THREAD

**Issue by skbeh** [kernitus/BukkitOldCombatMechanics#636]
## Information

* Server Version: Dionysus@5548e473708c8ed447446d9107db1e0000e31673

* OldCombatMechanics version: 1.11.0

* Server Log File: 
``` console
will be filled later :(
```

* OldCombatMechanics config file: Same as default

### To Reproduce
 
1. Use an auto clicker to change CPS to about more than 20.
2. Attack a player using sword with jump and move to make the hit critical.

### Expected Behaviour

The damage rate and knockback is same as normal CPS (about 8).

### Actual Behaviour

The player is knockbacked much more and the damage rate is much faster.
When using the latest dev build (3880ef041a2450f697d2716418c9129984d96240) of BukkitOldCombatMechanics, there is almost no delay between hits.

**Comment by kernitus** [comment]
Ignore the knockback for now, that would be a completely different issue. I need a debug log to know what is going on. Unfortunately "feel" doesn't help with coding, at least according to the extensive testing I have performed, the damage calculations are working fine.

**Comment by NotAlexNoyle** [comment]
I am still having this issue on my server. The CPS limits defined in attack-frequency in config.yml are not respected. It appears that the invulnerability animation is fixed, as is the knockback, but the damage accumulation from jitter clicking or auto clicking over the CPS limit goes through anyway. What kind of dev log would help you?

**Comment by kernitus** [comment]
@NotAlexNoyle The `attack-frequency` does not set hard limits, because you can still be overdamaged by an attack of a higher value than the previous one while immune. You need to enable `debug` mode at the bottom of the config and get the log in the chat from the attacker and defender's perspectives - which shows exactly how they were damaged and why.

**Comment by kernitus** [comment]
@skbeh I have done some extra testing, including automated testing with multiple attacks within a very short timeframe. I see nothing to indicate the attack damage is not working as intended. If you do not think that is the case, please provide some logs and perhaps a video so I can help.

**Comment by skbeh** [comment]
@kernitus Please reopen this. See https://github.com/kernitus/BukkitOldCombatMechanics/issues/665#issuecomment-1647468766.
