### ISSUE TITLE
Feature that changes the base attack speed. (1.8 has higher base damage than newer versions)

### ISSUE THREAD

**Issue by pbcairo** [kernitus/BukkitOldCombatMechanics#647]
## Problem
I found that in 1.8, I need to hit the pig (without weapons or tools) 7 times *(I'm aware of the Invulnerability time)*, but I need to hit 10 times in 1.19. I just confirmed that 1.8 has 1.5 base damage while 1.19 has 1.0 base damage.

## Proposed solution
Make a feature that changes the base attack damage for players, defaults to 1.5.

## Alternative solutions
- Make my own plugin that changes the base attack damage to 1.5
- Make a repeating command block and do `/attribute @a generic.attack_damage base set 1.5`.

**Comment by kernitus** [comment]
The only time when attacking by hand dealt more than 1 damage (half a heart) was in the Minecraft betas, and that was a very long time ago. I have no idea what you are talking about but you either calculated something wrong or are experiencing some other effect / plugins interfering. If you really want to see the values involved just use something like the Healthbar plugin.

**Comment by pbcairo** [comment]
made a plugin that logs the damage to the console it was 1.5 on Java 1.8.8. unsure if it's Spigot exclusive but ok
