### ISSUE TITLE
Errors in console

### ISSUE THREAD

**Issue by AggerTV** [kernitus/BukkitOldCombatMechanics#652]
## Information

* Server Version: Paper version git-Paper-388 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 57f1157)

* OldCombatMechanics version: 1.11.0

* Server Log File:  https://gist.github.com/AggerTV/2efca8e2a8acae9a915e47873234feb2

* OldCombatMechanics config file:  https://gist.github.com/AggerTV/f7036001cbd33ecd97daf93354b49569

## Problem Description

I don't know what's causing this, I just saw the errors in console and thought you wanted to know

**Comment by rayzr522** [comment]
thanks for reporting this :) some other plugins do some... very strange things with the scoreboard & team system that have ended up breaking the way we implemented the player collision module, so we've had to make some changes lately to improve compatibility. could you try the [latest dev build](https://ci.rayzr.dev/job/OldCombatMechanics/137/) and see if the errors are still present?
