### ISSUE TITLE
packet warning

### ISSUE THREAD

**Issue by richardwhateverr** [kernitus/BukkitOldCombatMechanics#653]
## Information

* Server Version: 
* Paper 1.19.4

* OldCombatMechanics version: 
* Jenkins Build 137

* Server Log File: 
``` console
XYZ joins the server
[00:07:02 WARN]: [OldCombatMechanics] Received a packet that is not NMS: class io.netty.buffer.PooledUnsafeDirectByteBuf PooledUnsafeDirectByteBuf(ridx: 0, widx: 5, cap: 256) 
```

* OldCombatMechanics config file: 
``` yaml
default config
```

## Problem Description

I don't really know if it has consequences.

### To Reproduce
 
1. player joins
2. warning
3.

**Comment by kernitus** [comment]
This just means another plugin is doing naughty stuff with packets, and it might interfere with OCM (especially with the no collisions module). Do you have any scoreboard plugins running?

**Comment by kernitus** [comment]
This is, after all, just a warning that something _could_ go wrong. If it works fine anyway there shouldn't be a problem. Maybe @I-Al-Istannen can give some more details on that.

**Comment by kernitus** [comment]
Alright, this means that unless there are some observable side-effects this can be safely ignored.
