### ISSUE TITLE
Armour Bug

### ISSUE THREAD

**Issue by srrawr11** [kernitus/BukkitOldCombatMechanics#655]
Server Version: PAPER 1.16.5
OldCombatMechanics version: 1.11.0
Server Log File: ---
OldCombatMechanics config file: https://pastebin.com/JEV4imS5

1 versus 1 with a player with full diamond armour with protection 4 and unb 3 (or netherite armour with the same enchantments)
hit on the player and causes 0 health points
just causes lost health points when you take off a piece of the armour
we used sharpness 5 on the swords (diamond and netherite)

**Comment by kernitus** [comment]
Please try this with the [latest test version](https://ci.rayzr.dev/job/OldCombatMechanics/), many changes have been made since to address the damage calculations.
