### ISSUE TITLE
Customizable damage for if cooldown is on/off.

### ISSUE THREAD

**Issue by MythicalTrashcan** [kernitus/BukkitOldCombatMechanics#657]
I have a server running the latest version of OldCombatMechanics and wanted to try making certain players have their cooldown on/off. Mixing them so one uses 1.8 combat and another uses 1.9 combat. One problem I noticed is that if you disable the old-tool-damage config option. 1.8 has a huge advantage because their axe attack is like 1.9 always having a full charge attack. 1.8 can kill a player in 3 hits with 1.8 combat. Of course, my first thought after that was to turn off old-tool-damage to make axes do 4 damage points and now, 1.9 does't do enough damage to the player and again, 1.8 has an advantage. To make a player have their cooldown turned off on join, there is a repeating command block that will turn on cooldown for a certain player.

Now, to the suggestion. Make an option that makes certain usernames have cooldown set to a value on join and make a config option to customize the damage for people with cooldown on/off.

If you want more detail, just ask.

**Comment by kernitus** [comment]
This involves a lot more than just one module to work properly - a lot of the damage modules are interlinked (e.g. you would also have to account for armour strength an potions). I have laid the groundwork for supporting this in the latest version. Having customisable per-user modules has been planned for a long time and will be implemented at some point in the future. If you like, you can add more detail to the original issue #179.
