### ISSUE TITLE
Eating gapple resets health boost effect

### ISSUE THREAD

**Issue by MisterLolxd2** [kernitus/BukkitOldCombatMechanics#664]
## Information

* Server Version: PaperSpigot 1.16.5

* OldCombatMechanics version: 1.12.1

* Server Log File:  None errors
``` console

```

* OldCombatMechanics config file: https://pastebin.com/8RSmdtGw
``` yaml

```

## Problem Description

If i have the HealthBoost III and i eating a golden apple takes our lives back.
1. Video (golden apple + healthboost): https://www.youtube.com/watch?v=uAAJSFDq9t8&ab_channel=Trawka
2. Video (durability bug? look a armor status) https://www.youtube.com/watch?v=SxjjZIdGI3U&ab_channel=scr1ptarina_
The problem with durability is if attacker has effect strength. Without this effect the durability just works.

### To Reproduce
 
1. Make healthboost ex. 3
2. Eat golden apple
3. Look

**Comment by kernitus** [comment]
1. These appear to be two completely separate issues. Please open a new issue for the armour durability one.
2. This seems to be related to the fix for #662, as the effects are now removed before being reapplied for compatibility reasons with weaker effects
