### ISSUE TITLE
1.20 smithing table & netherite upgrade template

### ISSUE THREAD

**Issue by Brottweiler** [kernitus/BukkitOldCombatMechanics#669]
## Problem
Smithing table now requires a nether upgrade template. You cannot use only netherite ingot to upgrade diamond armour to netherite. 

## Proposed solution
There could be a setting to automatically provide a netherite upgrade template in the smithing table, similar how enchanting tables work with lapis, or how brewing stands work with blaze powder.

An issue might be that there are trim templates too. But maybe if you have a trim template, it can overwrite the netherite upgrade template. 

- https://minecraft.fandom.com/wiki/Smithing_Template#Smithing_ingredient
- https://minecraft.fandom.com/wiki/Java_Edition_1.20#Items

**Comment by kernitus** [comment]
Interesting request, because netherite and smithing tables were not a thing in 1.8 and this is not directly combat related. 

1. What would be the main use-case for this?
2. If somebody opened the smithing table and placed a diamond item and a netherite ingot, should the plugin automatically fill in the other slot with a non-removable Netherite Upgrade template? What if they want to use something else?

**Comment by Brottweiler** [comment]
1. We use OldCombatMechanics for a special gamemode where players can enchant their stuff and make potions without also needing to get lapis and blaze powder, and with 1.20, we have a similar problem to solve since you need a netherite upgrade.
2. Practically, it would automatically have a netherite upgrade in there, but if you put in a armour trim, it would replace it.

I realise this might be out of scope for this plugin, since it focuses on 1.8 pvp and not changing anything that was introduced _after_ 1.8, so feel free to close this if you feel it is out of scope.

**Comment by kernitus** [comment]
We will keep this open for now but it is definitely low priority.

**Comment by kernitus** [comment]
It has been decided this is unfortunately out of scope for this plugin, which only deals with combat changes from 1.9 onwards.
