### ISSUE TITLE
Add way to change prefix.

### ISSUE THREAD

**Issue by jonaas13** [kernitus/BukkitOldCombatMechanics#670]
I have been using the plugin on my Kitpvp server for a while. 

It would be nice if I could change the prefix of the plugin, I can already change some messages in the config.
The current prefix doesn't match my server's chat style.

Example:
![image](https://github.com/kernitus/BukkitOldCombatMechanics/assets/7745750/5262e62f-e2a8-491f-9065-fbd483a1d3fd)

**Comment by kernitus** [comment]
Which messages do you currently use? It would be easier to allow customising just those, including the prefix

**Comment by jonaas13** [comment]
@kernitus 
I don't want to change the message I want to change the prefix [OCM].

This is the message for the Enderpearl delay:
`message: '&cYou must wait &7%ds&c before using an enderpearl again!'`

No way to edit the [OCM] prefix, currently.

**Comment by kernitus** [comment]
We can add the prefix as a customisable part of that message so that you can change it.

**Comment by jonaas13** [comment]
@kernitus that would fix my issue, thanks. 
Although it would make more sense to have a common prefix placeholder.

**Comment by pokameni** [comment]
Hi.

I'm just bumping this FR, i'm just waiting for this.
