### ISSUE TITLE
hit-frequency on mythicmobs not working

### ISSUE THREAD

**Issue by NeptuneDaFish** [kernitus/BukkitOldCombatMechanics#671]
Hello, i was trying out the hit-frequency recently and set it to 1 tick on mobs and players, works perfectly on vanilla mobs, but not on mythicmobs, it's like it has no effect, is there anything I could be doing wrong or is this a bug?

**Comment by NeptuneDaFish** [comment]
After a bit more testing i realised that the hit-frequency works as inteded only if i reload the plugin after i spawn the mob

**Comment by kernitus** [comment]
This implies that mythicmobs is not calling the `CreatureSpawnEvent` like entities are supposed to. When you reload the plugin it applies the new delay to all existing entities, otherwise this happens at entity spawn. Evidently mythicmobs is not letting other plugins know a spawn happened.

**Comment by NeptuneDaFish** [comment]
Alright, say i made a script using another plugin that reloads the oldcombatplugin every 2 ticks, all works well, except is there any way to disable the output in the console when the plugin reloads?

**Comment by kernitus** [comment]
That seems like a terrible idea, it would be incredibly computationally expensive to run every 2 ticks. Through a lot of digging I have found MythicMobs has [an API](https://git.mythiccraft.io/mythiccraft/MythicMobs/-/wikis/API) that can be used to know when a MythicMob is spawned.

**Comment by kernitus** [comment]
@NeptuneDaFish Cannot reproduce this at all. If I spawn a mythic mob with `/mythicmobs mobs spawn GIANT` it calls the `CreatureSpawnEvent` just like all mobs and applies the hit delay.
