### ISSUE TITLE
Sentinel/Citizens NPC conflict

### ISSUE THREAD

**Issue by Latestion** [kernitus/BukkitOldCombatMechanics#673]

**Comment by kernitus** [comment]
Could you please add more detail so we can help?

1. What version of the plugin and Spigot are you running?
2. What do you mean by "stop working", what do you expect to happen and what happens instead?

**Comment by Latestion** [comment]
Hey sorry for the lack of information.

I am running 1.19.4 and the latest version of Combat plugin


By stop working meant, for some reason my sentinel/citizens npc mess up (don't do damage or move around as they are supposed to), so is it possible to ignore any Old Combat Mechanics for NPC's?

**Comment by Latestion** [comment]
I think every Citizens NPC has the metadata: "NPC".

**Comment by kernitus** [comment]
It is possible but these issues should not be arising at all, the calculations are applies to entities of all origins equally. OCM also does not affect the way entities move, so there may be some other plugins interfering too. Do you have a list of plugins active?

**Comment by Latestion** [comment]
Heres the list:
![image](https://github.com/kernitus/BukkitOldCombatMechanics/assets/51133083/249b207f-139e-4d08-a4d5-f2fe545f9c7a)

But I am pretty sure its OCM because we the moment we removed it, it worked fine!

**Comment by BankAccounts** [comment]
Did you fix the problem above?

**Comment by Latestion** [comment]
Hey, any updates on this?

**Comment by kernitus** [comment]
> Hey sorry for the lack of information.
> 
> I am running 1.19.4 and the latest version of Combat plugin
> 
> By stop working I meant, for some reason my sentinel/citizens npc mess up (don't do damage or move around as they are supposed to), so is it possible to ignore any Old Combat Mechanics for NPC's?

This is completely the wrong request. OCM should apply equally to NPCs as it does to real players and mobs. If that is not the case, please provide more details so that this can be fixed.

**Comment by kernitus** [comment]
Merged into #735. NPCs should be treated the same as mobs.
