### ISSUE TITLE
Toggling shield causes duping

### ISSUE THREAD

**Issue by Wheat-guy** [kernitus/BukkitOldCombatMechanics#676]
On 1.20.1
If you enable putting items in the offhand slot in the config file:
When you hold a placeable item in your offhand slot and then toggle shield, if you continue holding your sword and try placing the item from your offhand, the amount of item in offhand won't actually change. Sometimes it doesn't happen though. Sometimes it even removes everything from the offhand slot.

**Comment by s0me0ne-coder** [comment]
the plugin doesnt save blocking state across restarts meaning if you hold right click to swordblock and open pause menu to disconnect and server restarts before you reconnect you can casually take out the shield from your offhand

**Comment by kernitus** [comment]
1. Please fill in the issue template properly. We need to know the details of your setup to be able to help.
2. @s0me0ne-coder that sound like a completely different issue. You can open up a new ticket for that.

**Comment by ant-7802** [comment]
yeah this is a bug on my server too, when will this be fixed?
