### ISSUE TITLE
Ability to hide hit delay indicator

### ISSUE THREAD

**Issue by Jaefaa** [kernitus/BukkitOldCombatMechanics#681]
* Server Version: spigot 1.12.2

* OldCombatMechanics version: latest version from spigot page

When you hit your oponent or swing your wepon somtimes the 1.12 hit delay icon apears under your crossair. Is there a way to disable this?

### To Reproduce
1. swing your sword
2. or swing your sword at a player/mob

**Comment by kernitus** [comment]
Not sure if it can be disabled completely, but it should only flash for a very short period of time if you have no combat delay. Is that a problem?

**Comment by kernitus** [comment]
No idea, maybe with packet manipulation. @rayzr522 or @I-Al-Istannen might know.

Why do you find it a major issue? It shouldn't affect gameplay, it is just a cosmetic artefact.

**Comment by I-Al-Istannen** [comment]
I am not sure sadly, but I would expect that to be handled completely by the client. There isn't really much to be communicated by the server (the cooldown is determined by the NBT data, I think) so I don't believe there is any packet sent to show it.

I think you can disable the indicator in your minecraft settings and change it using a resource pack, is that enough?

**Comment by Jaefaa** [comment]
No, I need it disabled for all players server wide.

**Comment by Jaefaa** [comment]
I'm on 1.8.9 and using 1.12.2 as server version.

**Comment by kernitus** [comment]
Unfortunately I don't believe this is actually possible from the server side. If you find a valid method or another plugin doing this, let us know.
