### ISSUE TITLE
The Residence has PVP disabled, but players can use fishing rods to inflict damage on other players.

### ISSUE THREAD

**Issue by 3154311518** [kernitus/BukkitOldCombatMechanics#682]
paper-1.12.2
OldCombatMechanics-1.12.2

The Residence has PVP disabled, but players can use fishing rods to inflict damage on other players.

The same applies to other plugins; as long as it's a PVP-disabled area, players can use fishing rods to inflict damage on other players.

**Comment by kernitus** [comment]
Can you list out exactly which plugins this is a problem for? Then we might be able to look at how they are handling damage events

**Comment by kernitus** [comment]
Fixed in ab69cf4
