### ISSUE TITLE
Weakness effect

### ISSUE THREAD

**Issue by Sharyx** [kernitus/BukkitOldCombatMechanics#686]
Hello, I found a bug in dev build #179. I applied weakness effect to zombie and to me. It was potion of weakness with 4 minutes duration.
Then I was hit by a zombie and I get a looot of hearts from absorption effect. My minecraft became very laggy.
To reproduce this error throw potion of weakness at any mob then throw potion of weakness at you and let the mob hit you. 
I tried this with default config settings.

**Comment by kernitus** [comment]
Fixed in 13b3147
