### ISSUE TITLE
Placeholder for combat mode

### ISSUE THREAD

**Issue by NigthDay** [kernitus/BukkitOldCombatMechanics#687]
Hello! I would like there to be a placeholder that indicates when the player has oldcombat activated or deactivated, it is an option that I currently need and it would help me a lot in what I am trying to do, and clearly also for someone else who finds it a function.

**Comment by kernitus** [comment]
Can you elaborate on what "placeholder" means and what it would look like?

**Comment by NigthDay** [comment]
> Can you elaborate on what "placeholder" means and what it would look like?

something like %ocm_player_is_toggle% == true or false (yes or no)

**Comment by kernitus** [comment]
Are you talking about [PlaceholderAPI](https://www.spigotmc.org/resources/placeholderapi.6245/)?

**Comment by kernitus** [comment]
Apparently we already had PlaceholderAPI support. I have updated it for the upcoming `modeset` functionality. If you would like to try the [newest test build](https://ci.rayzr.dev/job/OldCombatMechanics) with the `%ocm_modeset%` placeholder.

**Comment by NigthDay** [comment]
not working
