### ISSUE TITLE
Reach is 4 blocks, but needs to be configurable to less. 4 blocks is beyond vanilla.

### ISSUE THREAD

**Issue by karlheidar** [kernitus/BukkitOldCombatMechanics#689]
## Problem
1.20.2 - Problem or feature? Reach is 4 blocks, but needs to be configurable to less. 4 blocks is beyond vanilla.
I am using the plugin to disable hit cooldown, but it changes the mechanics of the reach.

**Comment by karlheidar** [comment]
Scenario: Player with sharpness V sword can hit another player standing 4 blocks away with full damage.

**Comment by kernitus** [comment]
I have no idea how you observed this effect, we do not make any modification whatsoever to the hit detection code. We only modify the damage done after some entity is hit.

Do you have other plugins that might be tinkering with combat?
Can you provide more information about your setup?
