### ISSUE TITLE
The totem does not work I can't take it in 2 hands 

### ISSUE THREAD

**Issue by Honors34** [kernitus/BukkitOldCombatMechanics#695]
I'm trying to take the totem, but it won't take what should I do?
![Screenshot_20231215-035235](https://github.com/kernitus/BukkitOldCombatMechanics/assets/151669288/c01d0b7f-4877-48d5-a6bb-485e03bb6fa8)

**Comment by kernitus** [comment]
You probably just have `disable-offhand` enabled in the config.yml.
