### ISSUE TITLE
When i am add worlds in the config it wont work pls help me

### ISSUE THREAD

**Issue by AbduBakr7** [kernitus/BukkitOldCombatMechanics#703]
* Server Version: paper 1.20.2

* OldCombatMechanics version:  2.0.0

i am just did some changes in only worlds line
i added bws1 world its old mode not new and its not working its still new not old !!!
even the off hand i want to disable it not work !!
pls help me 

[config (2).txt](https://github.com/kernitus/BukkitOldCombatMechanics/files/13884677/config.2.txt)

**Comment by kernitus** [comment]
Please fill in the issue template correctly.

**Comment by AbduBakr7** [comment]
bro i mean disable worlds not working at all 
look at my config file 
and when i am delete the plugin i cant use my offhand never pls help me

**Comment by AbduBakr7** [comment]
[config.2.txt](https://github.com/kernitus/BukkitOldCombatMechanics/files/13925750/config.2.txt)

**Comment by kernitus** [comment]
> bro i mean disable worlds not working at all look at my config file and when i am delete the plugin i cant use my offhand never pls help me

Can you say this again but in a comprehensible human language?
