### ISSUE TITLE
Fishing Rods can push players in non-pvp regions

### ISSUE THREAD

**Issue by iLemon** [kernitus/BukkitOldCombatMechanics#709]
Running plugin 2.0.1 on 1.20.2 server.

When old-fishing-knockback.enabled = true, you can attach a fishing rod to a player, and it'll push them slightly, allowing you to move them around and out of spawn, etc.

Setting this config option to false resolves the issue.

**Comment by kernitus** [comment]
Is that not exactly the behaviour fishing rods used to have?

**Comment by FairGames** [comment]
Yea, revert this option back:
  # Whether the EntityDamageEvent should be used instead of the EntityDamageByEntityEvent
  # Set to true when using plugins like NCP that check range
  useEntityDamageEvent: false

**Comment by kernitus** [comment]
> Yea, revert this option back:
> 
> ```
>   # Whether the EntityDamageEvent should be used instead of the EntityDamageByEntityEvent
>   # Set to true when using plugins like NCP that check range
>   useEntityDamageEvent: false
> ```

That option never actually did anything - there was a bug in the code that has now been fixed.

**Comment by kernitus** [comment]
This is the behaviour intended for the `old-fishing-knockback` module
