### ISSUE TITLE
Disable player collisions does not work

### ISSUE THREAD

**Issue by UpSideDownApe** [kernitus/BukkitOldCombatMechanics#712]
**Trying to disable player collisions and it doesn't seem to work when enabling it**
running 1.20.2 with ViaVersion, ViaBackwards, ViaRewind

![image_2024-02-06_141142040](https://github.com/kernitus/BukkitOldCombatMechanics/assets/159108928/40e090a4-a460-4d58-95a0-b71a7573c3f7)

**Comment by kernitus** [comment]
Please fill in the issue template.
