### ISSUE TITLE
1.20.4 Team packet error

### ISSUE THREAD

**Issue by Glowing-Studios** [kernitus/BukkitOldCombatMechanics#730]
## Information

* Server Version: PurPur 1.20.4

* OldCombatMechanics version: 2.0.1

https://mcpaste.io/93209faf854c1416

<details><summary>Server Log</summary>
  
``` console

```
</details>

https://mcpaste.io/bfcdeec127e6f09a
<details><summary>config.yml</summary>
  
``` yaml

```
</details>

## Problem Description

If you are running a KOTH with the AxKoth plugin and someone is killed, you get huge warn logs per death and this is a big problem with 3 koth per day and more than 30 players.

### To Reproduce
 
1. Start AxKoth koth
2. kill somebody
3. watch console

### Expected Behaviour

Better case, I shouldn't get any of these errors, maybe?

### Actual Behaviour

Apart from not seeing the console history monitored because of all the logs, nothing. No performance problems or very low and not noticeable.

**Comment by kernitus** [comment]
That's just a packet incompatibility error. It should already be fixed in the [newest test version](https://ci.rayzr.dev/job/OldCombatMechanics/).

**Comment by Glowing-Studios** [comment]
> That's just a packet incompatibility error. It should already be fixed in the [newest test version](https://ci.rayzr.dev/job/OldCombatMechanics/).

Wow. Thank you for your quick work.
