### ISSUE TITLE
Bug with empty messages

### ISSUE THREAD

**Issue by CheckMarvin** [kernitus/BukkitOldCombatMechanics#736]
I requested the pull request https://github.com/kernitus/BukkitOldCombatMechanics/issues/714 and you accepted and released it a few days ago. 

But if I use `mode-set: ""` it appears an empty message in chat:
![image](https://github.com/kernitus/BukkitOldCombatMechanics/assets/132604732/29bdbe32-bdab-4c58-9814-30de262a089c)

Did I something wrong or does your logic not work?

Best regards

**Comment by SrBedrock** [comment]
@CheckMarvin What version of the plugin, could you send me an example of the config.yml?

**Comment by SrBedrock** [comment]
@CheckMarvin fixed with #737

**Comment by CheckMarvin** [comment]
Thank you, it works :D
