### ISSUE TITLE
Problem with the fishing rod

### ISSUE THREAD

**Issue by jfcatano** [kernitus/BukkitOldCombatMechanics#740]
## Information

* Server Version: 1.20.4

* OldCombatMechanics version: 2.0.2 

* Server Log File: No errors.
<details><summary>Server Log</summary>
  
``` console

```
</details>

* OldCombatMechanics config file: Default config.
<details><summary>config.yml</summary>
  
``` yaml

```
</details>

## Problem Description

Hello! In version 1.20.4 I am trying to make an ArenaPvP 1.8. The fishing rod visually goes backwards and then forwards... I don't know if it's an OCM bug or something else. Players complain about this as it is inappropriate and makes the server playable worse.

### To Reproduce
 
1.
2.
3.

**Comment by kernitus** [comment]
Can you elaborate on what you mean by "The fishing rod visually goes backwards and then forwards"? Maybe provide a video?
