### ISSUE TITLE
Can you update one, disable the heart -shaped function during the attack? My server version is 1.20.4

### ISSUE THREAD

**Issue by Fy-MoMing** [kernitus/BukkitOldCombatMechanics#743]
Can you update one, disable the heart -shaped function during the attack? My server version is 1.20.4

**Comment by kernitus** [comment]
Can you explain more what feature you are talking about?

**Comment by Fy-MoMing** [comment]
For example, this plug-in
https://www.spigotmc.org/resources/nomoredamageeffect.38139/
But it does not support 1.20.4

**Comment by kernitus** [comment]
I'm not sure that is in scope for this plugin. This doesn't seem to affect combat.
