### ISSUE TITLE
Discord Server List

### ISSUE THREAD

**Issue by CheckMarvin** [kernitus/BukkitOldCombatMechanics#751]
I am in search of an official OCM discord server because i would like to have a list of servers which use OCM.

Maybe you can create some channels, where users can write in their minecraft server. You could create a "minigame" channel, a "citibuild" one and so on.

I personally would like to explore other minigame servers which are in use of the old combats.

**Comment by kernitus** [comment]
There is no official discord server for OCM. I believe @rayzr522 runs a discord server where you might find other people using the plugin.

**Comment by CheckMarvin** [comment]
Can you send me an invite link?

**Comment by rayzr522** [comment]
my server is no longer around, unfortunately (closed due to inactivity and my diverging interests)

**Comment by kernitus** [comment]
Sorry but it seems we don't have a discord server.
