### ISSUE TITLE
Items Getting Deleted

### ISSUE THREAD

**Issue by lowercasebtw** [kernitus/BukkitOldCombatMechanics#770]
When switching between dimensions (nether/end), if my inventory is full and I have a item in my offhand, it deletes the item.

I however have made the config use the same pvp modset in both dimensions however upon switching, it still says switching modsets and unequips my offhand.

**Comment by kernitus** [comment]
Please follow the issue template. I have no idea what version of the plugin, the server you are running, what config etc

**Comment by lowercasebtw** [comment]
The server I was on with the issue has since been deleted/I can't get those configs. Sorry

**Comment by kernitus** [comment]
Are you able to reproduce it on a new server?

**Comment by kernitus** [comment]
Cannot reproduce.
