### ISSUE TITLE
when i use the RMB i have a shield, and the shield reduce the damage ... all is good just this it's very bad . it's bug ?

### ISSUE THREAD

**Issue by Tchoupi007** [kernitus/BukkitOldCombatMechanics#773]
## Information

* Server Version: 

* OldCombatMechanics version: 

* Server Log File: 
<details><summary>Server Log</summary>
  
``` console

```
</details>

* OldCombatMechanics config file: 
<details><summary>config.yml</summary>
  
``` yaml

```
</details>

### To Reproduce
 
1.
2.
3.

**Comment by Tchoupi007** [comment]
Server Version: 1.21.1
OldCombatMechanics version:
Server Log File:
Server Log: don't have
OldCombatMechanics config file: 2.0.4
config.yml .
Problem Description : when i use the RMB i have a shield, and the shield reduce the damage ... all is good just this it's very bad . it's bug ?

Steps to reproduce the behavior:
1. equip sword
2. click RMB
3. you can see the shield

**Comment by kernitus** [comment]
So what's the actual problem?
